export const SharedTexts = {
  BrandName: "آتیس",
  BrandInitial: "آ",
  BrandDescription: "آسانسور و پله‌برقی",
  FormTitle: "فرم اطلاعات مشتری",
  FormEnglishTitle: "Customer Information Form",
  DocumentCode: "AT SLS 00000 FRM 001 00",
  LastFormUpdateDate: "تاریخ آخرین بروزرسانی فرم: ۱۴۰۳/۰۶/۱۸",
  PageNumber: "صفحه ۱ از ۱",
  VisitDate: {
    Label: "تاریخ بازدید",
    Day: "روز",
    Month: "ماه",
    Year: "سال",
  },
  VisitCoordinationPhone: "تلفن جهت هماهنگی بازدید",
  ReferenceNumber: "شماره مرجع آر اِن",
  ProjectName: "نام پروژه",
  ProjectExpertise: "کارشناسی پروژه",
  Reference: "مرجع",
  EmployerSpecifications: "مشخصات کارفرما",
  EmployerName: "نام کارفرما",
  RequesterName: "نام درخواست کننده",
  Email: "پست الکترونیکی",
  ContactNumber: "شماره تماس",
  ProjectAddress: "آدرس پروژه",
  Province: "استان",
  County: "شهرستان",
  ProductSpecifications: "مشخصات محصول",
  NumberOfUnits: "تعداد دستگاه",
  NumberOfStops: "تعداد توقف",
  ElevatorType: {
    Label: "نوع آسانسور",
    Options: ["هیدرولیک", "گیربکس", "گیرلس با موتورخانه ام‌آر", "گیرلس بدون موتورخانه ام‌آر‌ال"],
  },
  UsageType: {
    Label: "نوع کاربری",
    Options: ["مسافربر", "باربر", "بیمارستانی تخت‌بر", "برانکاردبر", "خودروبر", "مون شارژ", "صنعتی آی‌پی", "ضدانفجار زون"],
  },
  EnvironmentType: "نوع محیط",
  ElevatorSpeed: "سرعت آسانسور: متر بر ثانیه",
  Capacity: "ظرفیت",
  DoorSpecifications: "مشخصات درب",
  DoorType: {
    Label: "نوع درب",
    Options: ["تمام اتوماتیک", "نیمه اتوماتیک"],
  },
  DoorOpeningType: {
    Label: "بازشوی درب",
    Options: ["چپ/راست", "سانترال"],
  },
  FloorDoorArrangement: {
    Label: "جانمایی درب طبقه",
    Options: ["تک درب", "دو درب در مجاور", "تونلی"],
  },
  DoorWidth: "عرض درب",
  DoorHeight: "ارتفاع درب",
  DoorStainlessSteelType: "نوع استیل درب",
  ShaftSpecifications: "مشخصات چاه",
  ShaftIronwork: {
    Label: "آهنکشی چاه",
    Options: ["دارد", "ندارد"],
  },
  FoundationIntrusionIntoShaft: {
    Label: "آیا فنداسیون به داخل چاه نفوذ کرده است؟",
    Options: ["بلی", "خیر"],
  },
  IsShaftSuspended: {
    Label: "آیا چاه معلق است؟",
    Options: ["بلی", "خیر"],
  },
  CanPitBeDemolished: {
    Label: "امکان تخریب چاله وجود دارد؟",
    Options: ["بلی", "خیر"],
  },
  IsShaftSurroundingOpen: {
    Label: "آیا فضای اطراف چاه باز است؟",
    Options: ["بلی", "خیر"],
  },
  ShaftSurroundingCoveringType: {
    Label: "نوع پوشش اطراف چاه",
    Options: ["سفالی", "بتنی", "بلوک سیمانی", "دیوار برشی"],
  },
  ShaftWidth: "عرض چاه",
  ShaftDepth: "عمق چاه",
  ShaftHeight: "ارتفاع چاه",
  PitHeightWithoutFlooring: "ارتفاع پیت بدون کف‌سازی",
  OverheadWithoutFlooring: "اورهد بدون کف‌سازی",
  TravelLength: "طول تراول",
  RequestedPackageType: "نوع پکیج درخواستی",
  Description: "توضیحات",
  SalesExpertSignature: "امضا کارشناس فروش",
  SalesManagerApproval: "تایید مدیر فروش",
  Common: {
    Search: "جستجو",
    Edit: "ویرایش",
    Delete: "حذف",
    Cancel: "انصراف",
    ConfirmDelete: "حذف شود",
    ApplyFilters: "اعمال فیلترها",
    ClearFilters: "پاک کردن فیلترها",
    All: "همه",
    From: "از",
    To: "تا",
  },
  Errors: {
    RequiredField: "این فیلد الزامی است.",
    General: "خطایی برای این مورد پیش آمده است.",
  },
  Excel: {
    ExportErrorTitle: "خطا در دریافت اکسل",
    ExportErrorMessage: "فایل اکسل آماده نشد. لطفاً دوباره تلاش کنید.",
    NoFileSelected: "فایلی انتخاب نشده است.",
    WorksheetNotFound: "کاربرگ (worksheet) یافت نشد.",
    UnknownError: "خطایی برای این مورد پیش آمده است.",
  },
  Pagination: {
    PageSizeLabel: "تعداد در صفحه",
    SummaryTemplate: "نمایش {from} تا {to} از {total} مورد",
    EmptySummary: "موردی برای نمایش وجود ندارد.",
    AriaLabel: "صفحه‌بندی",
    FirstPage: "صفحه اول",
    PreviousPage: "صفحه قبل",
    NextPage: "صفحه بعد",
    LastPage: "صفحه آخر",
    Page: "صفحه {page}",
    Dots: "صفحه‌های بیشتر",
  },
  PageTitle: {
    Template: "{currentPageTitle} - سامانه مدیریت آتیس",
    Suffix: "سامانه مدیریت آتیس",
    Separator: "-",
  },
  PageTitles: {
    Login: "ورود",
    Dashboard: "داشبورد",
    Customers: "مشتریان",
    AddCustomer: "ثبت مشتری جدید",
    EditCustomer: "ویرایش مشتری",
    Projects: "پروژه‌ها",
    Reports: "گزارش‌ها",
    Users: "کاربران",
    Roles: "نقش‌ها و دسترسی‌ها",
    Profile: "پروفایل",
    About: "درباره",
  },
  Navigation: {
    Dashboard: "داشبورد",
    Crm: "مدیریت مشتریان",
    Customers: "مشتریان",
    Projects: "پروژه‌ها",
    Reports: "گزارش‌ها",
    Settings: "تنظیمات",
    Users: "کاربران",
    Roles: "نقش‌ها و دسترسی‌ها",
    Profile: "پروفایل",
  },
  Dashboard: {
    FeaturedModuleBadge: "اصلی",
    WelcomePrefix: "خوش آمدید،",
    WelcomeSuffix: "این داشبورد وضعیت بخش‌های اصلی ERP آتیس را نمایش می‌دهد.",
  },
  CommandPalette: {
    OpenButtonLabel: "فرمان‌ها",
    ModalTitle: "دسترسی سریع",
    SearchPlaceholder: "جستجو با نام فرمان یا کد",
    EmptyState: "فرمانی پیدا نشد.",
    CodeLabel: "کد",
    CodeHint: "کدهای نمونه: 1101، 1100، 1000",
    Commands: {
      Dashboard: "داشبورد",
      CustomerList: "فهرست مشتریان",
      NewCustomer: "ثبت مشتری جدید",
      ProjectList: "فهرست پروژه‌ها",
      Reports: "گزارش‌ها",
      Users: "مدیریت کاربران",
      Roles: "مدیریت نقش‌ها",
      Profile: "پروفایل کاربری",
    },
  },
  Profile: {
    PermissionCountLabel: "مجوز",
  },
  Layout: {
    HeaderTitle: "پنل مدیریت آتیس",
    HeaderSubtitle: "سامانه داخلی آسانسور و پله‌برقی",
    SidebarTitle: "منوی اصلی",
    SidebarSearchPlaceholder: "جستجو در منو",
    SidebarNoResults: "گزینه‌ای پیدا نشد.",
    MobileMenuLabel: "باز کردن منو",
    CloseMobileMenuLabel: "بستن منو",
    ComingSoonBadge: "به‌زودی",
  },
  DeleteConfirmation: {
    Title: "تایید حذف",
    Message: "آیا از حذف {entityType} «{entityName}» مطمئن هستید؟",
    DefaultDescription: "این عملیات در جریان فعلی قابل بازگشت نیست.",
  },
  DatePicker: {
    Placeholder: "انتخاب تاریخ",
    MobileOk: "تایید",
    MobileCancel: "انصراف",
  },
} as const;
