export const CrmTexts = {
  Customers: {
    PageDescription: "مدیریت مشتریان CRM آتیس، ثبت فرم اطلاعات مشتری، پیگیری فروش و نگهداری جریان نمونه در مرورگر.",
    NewCustomerButton: "مشتری جدید",
    EditCustomerTitle: "ویرایش مشتری",
    AddCustomerTitle: "ثبت مشتری جدید",
    Table: {
      Code: "کد",
      Source: "منبع جذب",
      SalesExpert: "کارشناس فروش",
      Priority: "اولویت",
      LastContact: "آخرین تماس",
      NextStep: "گام بعدی",
      EstimatedValue: "ارزش تخمینی",
      Status: "وضعیت",
      Actions: "عملیات",
      EditAction: "ویرایش مشتری",
      DeleteAction: "حذف مشتری",
      EmptyState: "هنوز مشتری‌ای ثبت نشده است.",
      FilteredEmptyState: "مشتری‌ای با این فیلترها پیدا نشد.",
    },
    Filters: {
      Title: "فیلترهای فهرست مشتریان",
      Description: "برای محدود کردن گزارش مشتریان، فیلترهای موردنیاز را انتخاب کنید.",
      ToggleOpen: "نمایش فیلترها",
      ToggleClose: "بستن فیلترها",
      ActiveCount: "{count} فیلتر فعال",
      GeneralSearch: "جستجوی کلی",
      GeneralSearchPlaceholder: "نام کارفرما، درخواست‌کننده، پروژه، شماره تماس یا گام بعدی",
      VisitDateFrom: "تاریخ بازدید از",
      VisitDateTo: "تاریخ بازدید تا",
      LastContactFrom: "آخرین تماس از",
      LastContactTo: "آخرین تماس تا",
      EstimatedValueContains: "ارزش تخمینی شامل",
      EstimatedValuePlaceholder: "مثلاً میلیارد یا 4.8",
      NumberOfStopsFrom: "تعداد توقف از",
      NumberOfStopsTo: "تعداد توقف تا",
      NumberOfUnitsFrom: "تعداد دستگاه از",
      NumberOfUnitsTo: "تعداد دستگاه تا",
      CountyDisabledPlaceholder: "ابتدا استان را انتخاب کنید",
    },
    Excel: {
      ReceiveButton: "دریافت اکسل",
      FileName: "atis-customers",
      SheetName: "مشتریان",
    },
    SalesExpertOptions: ["کارشناس فروش 1", "کارشناس فروش 2", "کارشناس فروش 3", "کارشناس فروش 4"],
    Form: {
      BasicInformationSection: "اطلاعات پایه پروژه",
      BasicInformationDescription: "مشخصات اولیه درخواست، پروژه و هماهنگی بازدید.",
      EmployerInformationDescription: "اطلاعات کارفرما، درخواست‌کننده و مسیرهای تماس.",
      ProductInformationDescription: "نیاز اولیه مشتری درباره آسانسور یا پکیج درخواستی.",
      CrmTrackingSection: "اطلاعات پیگیری CRM",
      CrmTrackingDescription: "وضعیت فروش، گام بعدی و ارزش تخمینی فرصت.",
      SaveButton: "ذخیره مشتری",
      UpdateButton: "ذخیره ویرایش",
      CancelButton: "انصراف",
      BackToListButton: "بازگشت به فهرست مشتریان",
      FormPageDescription: "ثبت و ویرایش اطلاعات مشتری در یک فرم ساده، واکنش‌گرا و مناسب اپلیکیشن‌های ERP.",
      CustomerNotFoundTitle: "مشتری مورد نظر پیدا نشد.",
      CustomerNotFoundDescription: "برای ویرایش، یک مشتری معتبر را از فهرست انتخاب کنید.",
      RequiredFieldError: "این فیلد الزامی است.",
      UsageTypesPlaceholder: "نوع کاربری را انتخاب کنید",
      CoveringTypesPlaceholder: "نوع پوشش را انتخاب کنید",
      StatusLabel: "وضعیت پیگیری",
      PriorityLabel: "اولویت پیگیری",
      SourcePlaceholder: "مثلاً وب‌سایت، معرفی، مناقصه",
      DescriptionPlaceholder: "توضیحات تکمیلی مشتری، شرایط پروژه یا نکات بازدید",
      SalesExpertPlaceholder: "کارشناس فروش را انتخاب کنید",
      EstimatedValuePlaceholder: "مثلاً 4.8 میلیارد تومان",
      NextStepPlaceholder: "مثلاً هماهنگی بازدید فنی",
      NumberPlaceholder: "عدد یا مقدار",
      MeterPlaceholder: "مقدار بر حسب متر",
      SpeedPlaceholder: "مثلاً 1.6",
      CapacityPlaceholder: "مثلاً 10 نفره یا 1000 کیلوگرم",
      PackageTypePlaceholder: "نوع پکیج پیشنهادی/درخواستی",
      ProjectExpertisePlaceholder: "واحد یا کارشناس پروژه",
      ReferencePlaceholder: "نام معرف یا مرجع",
      ReferenceNumberPlaceholder: "شماره RN",
      VisitPhonePlaceholder: "شماره تماس هماهنگی بازدید",
      ProvincePlaceholder: "استان پروژه را انتخاب کنید",
      CountyPlaceholder: "شهرستان پروژه را انتخاب کنید",
    },
    Delete: {
      EntityType: "مشتری",
      Description: "با حذف این مشتری، اطلاعات فرم مشتری و وضعیت پیگیری از جریان نمونه مرورگر حذف می‌شود.",
    },
    PriorityLabels: {
      low: "پایین",
      medium: "متوسط",
      high: "بالا",
      urgent: "فوری",
    },
    StatusLabels: {
      new: "جدید",
      negotiating: "در حال مذاکره",
      visited: "بازدید انجام شد",
      needsFollowUp: "نیازمند پیگیری",
      proposalSent: "پیشنهاد ارسال شد",
    },
  },
  Projects: {
    PageDescription: "پروژه‌های نمونه بر اساس کارفرما، نوع آسانسور، فاز فروش، زمان‌بندی و برآورد بودجه.",
    NewProjectButton: "پروژه جدید",
    Table: {
      ProjectCode: "کد پروژه",
      CurrentPhase: "فاز فعلی",
      SalesExpert: "کارشناس فروش",
      NextDeadline: "ددلاین بعدی",
      EstimatedBudget: "بودجه تخمینی",
    },
  },
} as const;
