export const CrmTexts = {
  Customers: {
    PageDescription: "مدیریت مشتریان CRM آتیس، ثبت فرم اطلاعات مشتری، پیگیری فروش و نگهداری جریان نمونه در مرورگر.",
    NewCustomerButton: "مشتری جدید",
    EditCustomerTitle: "ویرایش مشتری",
    AddCustomerTitle: "ثبت مشتری جدید",
    Table: {
      Code: "کد",
      City: "شهر",
      Source: "منبع جذب",
      SalesExpert: "کارشناس فروش",
      Priority: "اولویت",
      LastContact: "آخرین تماس",
      NextStep: "گام بعدی",
      EstimatedValue: "ارزش تخمینی",
      Status: "وضعیت",
      Actions: "عملیات",
      EditAction: "ویرایش مشتری",
      DeleteAction: "حذف مشتری",
      EmptyState: "هنوز مشتری‌ای ثبت نشده است.",
    },
    Form: {
      BasicInformationSection: "اطلاعات پایه پروژه",
      BasicInformationDescription: "مشخصات اولیه درخواست، پروژه و هماهنگی بازدید.",
      EmployerInformationDescription: "اطلاعات کارفرما، درخواست‌کننده و مسیرهای تماس.",
      ProductInformationDescription: "نیاز اولیه مشتری درباره آسانسور یا پکیج درخواستی.",
      CrmTrackingSection: "اطلاعات پیگیری CRM",
      CrmTrackingDescription: "وضعیت فروش، گام بعدی و ارزش تخمینی فرصت.",
      SaveButton: "ذخیره مشتری",
      UpdateButton: "ذخیره ویرایش",
      CancelButton: "انصراف",
      BackToListButton: "بازگشت به فهرست مشتریان",
      FormPageDescription: "ثبت و ویرایش اطلاعات مشتری در یک فرم ساده، واکنش‌گرا و مناسب اپلیکیشن‌های ERP.",
      CustomerNotFoundTitle: "مشتری مورد نظر پیدا نشد.",
      CustomerNotFoundDescription: "برای ویرایش، یک مشتری معتبر را از فهرست انتخاب کنید.",
      RequiredFieldError: "این فیلد الزامی است.",
      UsageTypesPlaceholder: "نوع کاربری را انتخاب کنید",
      CoveringTypesPlaceholder: "نوع پوشش را انتخاب کنید",
      StatusLabel: "وضعیت پیگیری",
      PriorityLabel: "اولویت پیگیری",
      SourcePlaceholder: "مثلاً وب‌سایت، معرفی، مناقصه",
      DescriptionPlaceholder: "توضیحات تکمیلی مشتری، شرایط پروژه یا نکات بازدید",
      SalesExpertPlaceholder: "نام کارشناس فروش",
      EstimatedValuePlaceholder: "مثلاً ۴.۸ میلیارد تومان",
      NextStepPlaceholder: "مثلاً هماهنگی بازدید فنی",
      NumberPlaceholder: "عدد یا مقدار",
      MeterPlaceholder: "مقدار بر حسب متر",
      SpeedPlaceholder: "مثلاً ۱.۶",
      CapacityPlaceholder: "مثلاً ۱۰ نفره یا ۱۰۰۰ کیلوگرم",
      PackageTypePlaceholder: "نوع پکیج پیشنهادی/درخواستی",
      ProjectExpertisePlaceholder: "واحد یا کارشناس پروژه",
      ReferencePlaceholder: "نام معرف یا مرجع",
      ReferenceNumberPlaceholder: "شماره RN",
      VisitPhonePlaceholder: "شماره تماس هماهنگی بازدید",
    },
    Delete: {
      EntityType: "مشتری",
      Description: "با حذف این مشتری، اطلاعات فرم مشتری و وضعیت پیگیری از جریان نمونه مرورگر حذف می‌شود.",
    },
    PriorityLabels: {
      low: "پایین",
      medium: "متوسط",
      high: "بالا",
      urgent: "فوری",
    },
    StatusLabels: {
      new: "جدید",
      negotiating: "در حال مذاکره",
      visited: "بازدید انجام شد",
      needsFollowUp: "نیازمند پیگیری",
      proposalSent: "پیشنهاد ارسال شد",
    },
  },
  Projects: {
    PageDescription: "پروژه‌های نمونه بر اساس کارفرما، نوع آسانسور، فاز فروش، زمان‌بندی و برآورد بودجه.",
    NewProjectButton: "پروژه جدید",
    Table: {
      ProjectCode: "کد پروژه",
      CurrentPhase: "فاز فعلی",
      SalesExpert: "کارشناس فروش",
      NextDeadline: "ددلاین بعدی",
      EstimatedBudget: "بودجه تخمینی",
    },
  },
} as const;
