import { type CustomerRecord } from "@/modules/crm/types/customer.types";

export const emptyCustomerFormValues: Omit<CustomerRecord, "id"> = {
  visitDate: "1403/07/12",
  visitCoordinationPhone: "",
  referenceNumber: "",
  projectName: "",
  projectExpertise: "",
  reference: "",
  employerName: "",
  requesterName: "",
  contactNumber: "",
  email: "",
  projectAddress: "",
  provinceId: "",
  countyId: "",
  source: "",
  salesExpert: "",
  status: "new",
  priority: "medium",
  lastContact: "",
  nextStep: "",
  estimatedValue: "",
  numberOfUnits: "",
  numberOfStops: "",
  elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
  usageTypes: [],
  environmentType: "",
  elevatorSpeed: "",
  capacity: "",
  doorType: "تمام اتوماتیک",
  doorOpeningType: "سانترال",
  floorDoorArrangement: "تک درب",
  doorWidth: "",
  doorHeight: "",
  doorStainlessSteelType: "",
  shaftIronwork: "ندارد",
  foundationIntrusionIntoShaft: "خیر",
  isShaftSuspended: "خیر",
  canPitBeDemolished: "خیر",
  isShaftSurroundingOpen: "خیر",
  shaftSurroundingCoveringTypes: [],
  shaftWidth: "",
  shaftDepth: "",
  shaftHeight: "",
  pitHeightWithoutFlooring: "",
  overheadWithoutFlooring: "",
  travelLength: "",
  requestedPackageType: "",
  description: "",
};

export const defaultCustomers: CustomerRecord[] = [
  {
    ...emptyCustomerFormValues,
    id: 1001,
    visitDate: "1403/07/12",
    visitCoordinationPhone: "021-22000000",
    referenceNumber: "RN-1403-001",
    projectName: "برج سپهر",
    projectExpertise: "واحد فروش و فنی",
    reference: "وب‌سایت",
    employerName: "شرکت عمران سپهر",
    requesterName: "مهندس رضایی",
    contactNumber: "021-22000000",
    email: "customer1001@atis.example",
    projectAddress: "تهران، خیابان ولیعصر، برج سپهر",
    provinceId: "24",
    countyId: "405",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 1",
    status: "negotiating",
    priority: "high",
    lastContact: "1403/07/12",
    nextStep: "ارسال پیش‌فاکتور",
    estimatedValue: "4.8 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "12",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1",
    capacity: "8 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "24",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1002,
    visitDate: "1403/07/10",
    visitCoordinationPhone: "026-22001379",
    referenceNumber: "RN-1403-002",
    projectName: "مجتمع نگین",
    projectExpertise: "واحد فروش",
    reference: "معرفی مشتری قبلی",
    employerName: "مجتمع تجاری نگین",
    requesterName: "خانم احمدی",
    contactNumber: "026-22001379",
    email: "customer1002@atis.example",
    projectAddress: "البرز، بلوار اصلی، مجتمع نگین",
    provinceId: "31",
    countyId: "478",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "medium",
    lastContact: "1403/07/10",
    nextStep: "ثبت گزارش بازدید",
    estimatedValue: "3.2 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "8",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "تجاری",
    elevatorSpeed: "1.6",
    capacity: "10 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "25",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1003,
    visitDate: "1403/07/08",
    visitCoordinationPhone: "051-22002758",
    referenceNumber: "RN-1403-003",
    projectName: "بخش توسعه بیمارستان آتیه",
    projectExpertise: "واحد مناقصات",
    reference: "مناقصه",
    employerName: "بیمارستان آتیه",
    requesterName: "واحد تدارکات",
    contactNumber: "051-22002758",
    email: "customer1003@atis.example",
    projectAddress: "تهران، شهرک غرب، بیمارستان آتیه",
    provinceId: "24",
    countyId: "408",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 3",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "1403/07/08",
    nextStep: "هماهنگی بازدید فنی",
    estimatedValue: "6.1 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "8",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["بیمارستانی تخت‌بر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "1.75",
    capacity: "13 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "26",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1004,
    visitDate: "1403/07/05",
    visitCoordinationPhone: "031-22004137",
    referenceNumber: "RN-1403-004",
    projectName: "هتل آرامیس",
    projectExpertise: "واحد فنی",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "گروه هتل‌های آرامیس",
    requesterName: "مهندس کریمی",
    contactNumber: "031-22004137",
    email: "customer1004@atis.example",
    projectAddress: "مشهد، بلوار وکیل‌آباد، هتل آرامیس",
    provinceId: "10",
    countyId: "209",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "high",
    lastContact: "1403/07/05",
    nextStep: "پیگیری تایید مالی",
    estimatedValue: "9.5 میلیارد تومان",
    numberOfUnits: "3",
    numberOfStops: "14",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "هتل",
    elevatorSpeed: "0.63",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "27",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1005,
    visitDate: "1403/07/03",
    visitCoordinationPhone: "071-22005516",
    referenceNumber: "RN-1403-005",
    projectName: "برج پزشکان یاس",
    projectExpertise: "واحد فروش و فنی",
    reference: "تماس تلفنی",
    employerName: "تعاونی پزشکان یاس",
    requesterName: "دکتر پارسا",
    contactNumber: "071-22005516",
    email: "customer1005@atis.example",
    projectAddress: "اصفهان، خیابان چهارباغ، برج پزشکان",
    provinceId: "11",
    countyId: "236",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 1",
    status: "negotiating",
    priority: "high",
    lastContact: "1403/07/03",
    nextStep: "بازبینی نقشه چاه",
    estimatedValue: "5.4 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "10",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "1",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "28",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1006,
    visitDate: "1403/06/30",
    visitCoordinationPhone: "041-22006895",
    referenceNumber: "RN-1403-006",
    projectName: "سوله صنعتی آذر",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "شرکت صنعت آذر",
    requesterName: "آقای نادری",
    contactNumber: "041-22006895",
    email: "customer1006@atis.example",
    projectAddress: "تبریز، شهرک صنعتی، سوله آذر",
    provinceId: "4",
    countyId: "53",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "new",
    priority: "medium",
    lastContact: "1403/06/30",
    nextStep: "تماس اولیه",
    estimatedValue: "2.1 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "3",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "صنعتی",
    elevatorSpeed: "1.6",
    capacity: "8 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "29",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1007,
    visitDate: "1403/06/28",
    visitCoordinationPhone: "061-22008274",
    referenceNumber: "RN-1403-007",
    projectName: "مرکز خرید ساحل",
    projectExpertise: "واحد مناقصات",
    reference: "نمایندگی جنوب",
    employerName: "شرکت توسعه ساحل",
    requesterName: "خانم صفایی",
    contactNumber: "061-22008274",
    email: "customer1007@atis.example",
    projectAddress: "بندر عباس، بلوار ساحلی، مرکز خرید ساحل",
    provinceId: "23",
    countyId: "393",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "urgent",
    lastContact: "1403/06/28",
    nextStep: "ارسال طرح فنی",
    estimatedValue: "8.7 میلیارد تومان",
    numberOfUnits: "4",
    numberOfStops: "6",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "1.75",
    capacity: "10 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "30",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1008,
    visitDate: "1403/06/25",
    visitCoordinationPhone: "011-22009653",
    referenceNumber: "RN-1403-008",
    projectName: "مجتمع مسکونی باران",
    projectExpertise: "واحد فنی",
    reference: "اینستاگرام",
    employerName: "انبوه‌سازان باران",
    requesterName: "مهندس نوری",
    contactNumber: "011-22009653",
    email: "customer1008@atis.example",
    projectAddress: "رشت، گلسار، مجتمع باران",
    provinceId: "2",
    countyId: "17",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 4",
    status: "needsFollowUp",
    priority: "medium",
    lastContact: "1403/06/25",
    nextStep: "هماهنگی جلسه حضوری",
    estimatedValue: "3.9 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "7",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "0.63",
    capacity: "13 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "31",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1009,
    visitDate: "1403/06/22",
    visitCoordinationPhone: "076-22011032",
    referenceNumber: "RN-1403-009",
    projectName: "پردیس اداری نیایش",
    projectExpertise: "واحد فروش و فنی",
    reference: "همکاری معمار",
    employerName: "شرکت پردیس نیایش",
    requesterName: "آقای صادقی",
    contactNumber: "076-22011032",
    email: "customer1009@atis.example",
    projectAddress: "تهران، بزرگراه نیایش، پردیس اداری",
    provinceId: "24",
    countyId: "405",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 1",
    status: "proposalSent",
    priority: "high",
    lastContact: "1403/06/22",
    nextStep: "دریافت نظر مشاور",
    estimatedValue: "12.4 میلیارد تومان",
    numberOfUnits: "4",
    numberOfStops: "16",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "1",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "32",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1010,
    visitDate: "1403/06/20",
    visitCoordinationPhone: "025-22012411",
    referenceNumber: "RN-1403-010",
    projectName: "کلینیک مهر",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "کلینیک تخصصی مهر",
    requesterName: "خانم رستمی",
    contactNumber: "025-22012411",
    email: "customer1010@atis.example",
    projectAddress: "شیراز، معالی‌آباد، کلینیک مهر",
    provinceId: "8",
    countyId: "145",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "negotiating",
    priority: "medium",
    lastContact: "1403/06/20",
    nextStep: "ارسال لیست تجهیزات",
    estimatedValue: "2.7 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "5",
    elevatorType: "هیدرولیک",
    usageTypes: ["برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "1.6",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "33",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1011,
    visitDate: "1403/06/18",
    visitCoordinationPhone: "021-22013790",
    referenceNumber: "RN-1403-011",
    projectName: "انبار مرکزی پارس",
    projectExpertise: "واحد مناقصات",
    reference: "تماس تلفنی",
    employerName: "پخش پارس",
    requesterName: "آقای مولایی",
    contactNumber: "021-22013790",
    email: "customer1011@atis.example",
    projectAddress: "قم، شهرک صنعتی شکوهیه، انبار مرکزی",
    provinceId: "26",
    countyId: "433",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "low",
    lastContact: "1403/06/18",
    nextStep: "ثبت ابعاد نهایی",
    estimatedValue: "1.6 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "2",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "انبار",
    elevatorSpeed: "1.75",
    capacity: "8 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "34",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1012,
    visitDate: "1403/06/15",
    visitCoordinationPhone: "026-22015169",
    referenceNumber: "RN-1403-012",
    projectName: "برج نارنجستان",
    projectExpertise: "واحد فنی",
    reference: "معرفی مشتری قبلی",
    employerName: "شرکت نارنجستان",
    requesterName: "مهندس محمودی",
    contactNumber: "026-22015169",
    email: "customer1012@atis.example",
    projectAddress: "ساری، بلوار پاسداران، برج نارنجستان",
    provinceId: "3",
    countyId: "35",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "high",
    lastContact: "1403/06/15",
    nextStep: "بررسی اولیه نقشه",
    estimatedValue: "5.9 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "11",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "0.63",
    capacity: "10 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "35",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1013,
    visitDate: "1403/07/12",
    visitCoordinationPhone: "051-22016548",
    referenceNumber: "RN-1403-013",
    projectName: "پروژه تجاری زیتون",
    projectExpertise: "واحد فروش و فنی",
    reference: "مناقصه",
    employerName: "سرمایه‌گذاری زیتون",
    requesterName: "خانم حیدری",
    contactNumber: "051-22016548",
    email: "customer1013@atis.example",
    projectAddress: "اهواز، کیانپارس، پروژه زیتون",
    provinceId: "7",
    countyId: "111",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "1403/07/12",
    nextStep: "تکمیل اسناد مناقصه",
    estimatedValue: "7.8 میلیارد تومان",
    numberOfUnits: "3",
    numberOfStops: "9",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "1",
    capacity: "13 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "36",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1014,
    visitDate: "1403/07/10",
    visitCoordinationPhone: "031-22017927",
    referenceNumber: "RN-1403-014",
    projectName: "مجتمع اقامتی کوهستان",
    projectExpertise: "واحد فروش",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "گروه گردشگری کوهستان",
    requesterName: "آقای حاتمی",
    contactNumber: "031-22017927",
    email: "customer1014@atis.example",
    projectAddress: "کرمانشاه، طاق‌بستان، مجتمع اقامتی",
    provinceId: "6",
    countyId: "96",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 2",
    status: "proposalSent",
    priority: "medium",
    lastContact: "1403/07/10",
    nextStep: "انتظار تایید هیئت مدیره",
    estimatedValue: "4.3 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "6",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "هتل",
    elevatorSpeed: "1.6",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "37",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1015,
    visitDate: "1403/07/08",
    visitCoordinationPhone: "071-22019306",
    referenceNumber: "RN-1403-015",
    projectName: "پروژه مسکن آفتاب",
    projectExpertise: "واحد مناقصات",
    reference: "وب‌سایت",
    employerName: "تعاونی مسکن آفتاب",
    requesterName: "مهندس شمس",
    contactNumber: "071-22019306",
    email: "customer1015@atis.example",
    projectAddress: "یزد، صفاییه، پروژه آفتاب",
    provinceId: "22",
    countyId: "384",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "medium",
    lastContact: "1403/07/08",
    nextStep: "اصلاح جانمایی درب",
    estimatedValue: "6.2 میلیارد تومان",
    numberOfUnits: "3",
    numberOfStops: "9",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1.75",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "38",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1016,
    visitDate: "1403/07/05",
    visitCoordinationPhone: "041-22020685",
    referenceNumber: "RN-1403-016",
    projectName: "کارخانه بسته‌بندی خلیج",
    projectExpertise: "واحد فنی",
    reference: "نمایندگی جنوب",
    employerName: "صنایع غذایی خلیج",
    requesterName: "آقای امیری",
    contactNumber: "041-22020685",
    email: "customer1016@atis.example",
    projectAddress: "بوشهر، شهرک صنعتی، کارخانه خلیج",
    provinceId: "19",
    countyId: "354",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 4",
    status: "negotiating",
    priority: "high",
    lastContact: "1403/07/05",
    nextStep: "بازدید دوم فنی",
    estimatedValue: "3.5 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "4",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "صنعتی",
    elevatorSpeed: "0.63",
    capacity: "8 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "39",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1017,
    visitDate: "1403/07/03",
    visitCoordinationPhone: "061-22022064",
    referenceNumber: "RN-1403-017",
    projectName: "برج آسمان",
    projectExpertise: "واحد فروش و فنی",
    reference: "اینستاگرام",
    employerName: "گروه ساختمانی آسمان",
    requesterName: "خانم یوسفی",
    contactNumber: "061-22022064",
    email: "customer1017@atis.example",
    projectAddress: "قزوین، بلوار دانشگاه، برج آسمان",
    provinceId: "27",
    countyId: "438",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 1",
    status: "new",
    priority: "medium",
    lastContact: "1403/07/03",
    nextStep: "تماس جهت نیازسنجی",
    estimatedValue: "5.1 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "13",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1",
    capacity: "10 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "40",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1018,
    visitDate: "1403/06/30",
    visitCoordinationPhone: "011-22023443",
    referenceNumber: "RN-1403-018",
    projectName: "مرکز لجستیک شرق",
    projectExpertise: "واحد فروش",
    reference: "تماس تلفنی",
    employerName: "لجستیک شرق",
    requesterName: "آقای توسلی",
    contactNumber: "011-22023443",
    email: "customer1018@atis.example",
    projectAddress: "مشهد، جاده سرخس، مرکز لجستیک",
    provinceId: "10",
    countyId: "209",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "low",
    lastContact: "1403/06/30",
    nextStep: "ارسال گزارش ابعاد",
    estimatedValue: "1.9 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "2",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "انبار",
    elevatorSpeed: "1.6",
    capacity: "13 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "41",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1019,
    visitDate: "1403/06/28",
    visitCoordinationPhone: "076-22024822",
    referenceNumber: "RN-1403-019",
    projectName: "ساختمان اداری دیبا",
    projectExpertise: "واحد مناقصات",
    reference: "همکاری معمار",
    employerName: "شرکت دیبا سازه",
    requesterName: "مهندس دادگر",
    contactNumber: "076-22024822",
    email: "customer1019@atis.example",
    projectAddress: "تهران، سعادت‌آباد، ساختمان دیبا",
    provinceId: "24",
    countyId: "405",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "high",
    lastContact: "1403/06/28",
    nextStep: "دریافت تایید کارفرما",
    estimatedValue: "3.4 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "7",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "1.75",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "24",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1020,
    visitDate: "1403/06/25",
    visitCoordinationPhone: "025-22026201",
    referenceNumber: "RN-1403-020",
    projectName: "بازارچه اطلس",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "شرکت اطلس بازار",
    requesterName: "خانم فراهانی",
    contactNumber: "025-22026201",
    email: "customer1020@atis.example",
    projectAddress: "کرج، عظیمیه، بازارچه اطلس",
    provinceId: "31",
    countyId: "478",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "medium",
    lastContact: "1403/06/25",
    nextStep: "پیگیری پیش‌پرداخت",
    estimatedValue: "3.1 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "5",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "0.63",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "25",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1021,
    visitDate: "1403/06/22",
    visitCoordinationPhone: "021-22027580",
    referenceNumber: "RN-1403-021",
    projectName: "بیمارستان سلامت شمال",
    projectExpertise: "واحد فروش و فنی",
    reference: "مناقصه",
    employerName: "بیمارستان سلامت",
    requesterName: "واحد فنی",
    contactNumber: "021-22027580",
    email: "customer1021@atis.example",
    projectAddress: "رشت، بلوار نماز، بیمارستان سلامت",
    provinceId: "2",
    countyId: "17",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "1403/06/22",
    nextStep: "تکمیل مدارک فنی",
    estimatedValue: "10.2 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "10",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["بیمارستانی تخت‌بر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "1",
    capacity: "8 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "26",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1022,
    visitDate: "1403/06/20",
    visitCoordinationPhone: "026-22028959",
    referenceNumber: "RN-1403-022",
    projectName: "مجتمع ویلایی سرو",
    projectExpertise: "واحد فروش",
    reference: "اینستاگرام",
    employerName: "شرکت سرو شمال",
    requesterName: "آقای بهشتی",
    contactNumber: "026-22028959",
    email: "customer1022@atis.example",
    projectAddress: "نور، جاده ساحلی، مجتمع سرو",
    provinceId: "3",
    countyId: "38",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 2",
    status: "new",
    priority: "low",
    lastContact: "1403/06/20",
    nextStep: "ارسال کاتالوگ",
    estimatedValue: "1.4 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "3",
    elevatorType: "هیدرولیک",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1.6",
    capacity: "10 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "27",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1023,
    visitDate: "1403/06/18",
    visitCoordinationPhone: "051-22030338",
    referenceNumber: "RN-1403-023",
    projectName: "پالایشگاه نمونه",
    projectExpertise: "واحد مناقصات",
    reference: "مناقصه",
    employerName: "مهندسی انرژی نمونه",
    requesterName: "مهندس سلیمانی",
    contactNumber: "051-22030338",
    email: "customer1023@atis.example",
    projectAddress: "عسلویه، سایت صنعتی، پالایشگاه نمونه",
    provinceId: "19",
    countyId: "363",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "urgent",
    lastContact: "1403/06/18",
    nextStep: "بررسی الزامات ضدانفجار",
    estimatedValue: "8.9 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "5",
    elevatorType: "گیربکس",
    usageTypes: ["صنعتی آی‌پی", "ضدانفجار زون"],
    environmentType: "صنعتی",
    elevatorSpeed: "1.75",
    capacity: "13 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "28",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1024,
    visitDate: "1403/06/15",
    visitCoordinationPhone: "031-22031717",
    referenceNumber: "RN-1403-024",
    projectName: "دانشکده فنی آینده",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "دانشگاه آینده",
    requesterName: "خانم کیانی",
    contactNumber: "031-22031717",
    email: "customer1024@atis.example",
    projectAddress: "اصفهان، دانشگاه آینده، دانشکده فنی",
    provinceId: "11",
    countyId: "236",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "negotiating",
    priority: "medium",
    lastContact: "1403/06/15",
    nextStep: "تنظیم جلسه با مشاور",
    estimatedValue: "2.6 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "4",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "آموزشی",
    elevatorSpeed: "0.63",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "29",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1025,
    visitDate: "1403/07/12",
    visitCoordinationPhone: "071-22033096",
    referenceNumber: "RN-1403-025",
    projectName: "مرکز درمانی امید",
    projectExpertise: "واحد فروش و فنی",
    reference: "معرفی مشتری قبلی",
    employerName: "مرکز درمانی امید",
    requesterName: "دکتر عظیمی",
    contactNumber: "071-22033096",
    email: "customer1025@atis.example",
    projectAddress: "تبریز، ولیعصر، مرکز درمانی امید",
    provinceId: "4",
    countyId: "53",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 1",
    status: "proposalSent",
    priority: "high",
    lastContact: "1403/07/12",
    nextStep: "پیگیری تاییدیه فنی",
    estimatedValue: "4.9 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "7",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "1",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "30",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1026,
    visitDate: "1403/07/10",
    visitCoordinationPhone: "041-22034475",
    referenceNumber: "RN-1403-026",
    projectName: "برج مسکونی آریا",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "آریا سازه",
    requesterName: "مهندس لطیفی",
    contactNumber: "041-22034475",
    email: "customer1026@atis.example",
    projectAddress: "شیراز، قصردشت، برج آریا",
    provinceId: "8",
    countyId: "145",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "medium",
    lastContact: "1403/07/10",
    nextStep: "ثبت گزارش بازدید",
    estimatedValue: "5.7 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "12",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1.6",
    capacity: "8 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "31",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1027,
    visitDate: "1403/07/08",
    visitCoordinationPhone: "061-22035854",
    referenceNumber: "RN-1403-027",
    projectName: "پاساژ مینا",
    projectExpertise: "واحد مناقصات",
    reference: "تماس تلفنی",
    employerName: "سرمایه‌گذاری مینا",
    requesterName: "خانم سلطانی",
    contactNumber: "061-22035854",
    email: "customer1027@atis.example",
    projectAddress: "قم، خیابان جمهوری، پاساژ مینا",
    provinceId: "26",
    countyId: "433",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 3",
    status: "needsFollowUp",
    priority: "high",
    lastContact: "1403/07/08",
    nextStep: "ارسال نسخه اصلاحی پیشنهاد",
    estimatedValue: "3.8 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "6",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "1.75",
    capacity: "10 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "32",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1028,
    visitDate: "1403/07/05",
    visitCoordinationPhone: "011-22037233",
    referenceNumber: "RN-1403-028",
    projectName: "ساختمان ستاره شرق",
    projectExpertise: "واحد فنی",
    reference: "اینستاگرام",
    employerName: "ستاره شرق",
    requesterName: "آقای مرادی",
    contactNumber: "011-22037233",
    email: "customer1028@atis.example",
    projectAddress: "نیشابور، بلوار بعثت، ساختمان ستاره شرق",
    provinceId: "10",
    countyId: "210",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "medium",
    lastContact: "1403/07/05",
    nextStep: "تماس اولیه",
    estimatedValue: "2.9 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "8",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "0.63",
    capacity: "13 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "33",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1029,
    visitDate: "1403/07/03",
    visitCoordinationPhone: "076-22038612",
    referenceNumber: "RN-1403-029",
    projectName: "کارگاه قطعات دقیق",
    projectExpertise: "واحد فروش و فنی",
    reference: "وب‌سایت",
    employerName: "قطعات دقیق البرز",
    requesterName: "مهندس جمشیدی",
    contactNumber: "076-22038612",
    email: "customer1029@atis.example",
    projectAddress: "فردیس، شهرک صنعتی، کارگاه قطعات دقیق",
    provinceId: "31",
    countyId: "483",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 1",
    status: "negotiating",
    priority: "low",
    lastContact: "1403/07/03",
    nextStep: "نهایی کردن ظرفیت",
    estimatedValue: "1.2 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "2",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "صنعتی",
    elevatorSpeed: "1",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "34",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1030,
    visitDate: "1403/06/30",
    visitCoordinationPhone: "025-22039991",
    referenceNumber: "RN-1403-030",
    projectName: "پروژه اطلس غرب",
    projectExpertise: "واحد فروش",
    reference: "همکاری معمار",
    employerName: "اطلس غرب ایرانیان",
    requesterName: "خانم صابری",
    contactNumber: "025-22039991",
    email: "customer1030@atis.example",
    projectAddress: "کرمانشاه، الهیه، پروژه اطلس غرب",
    provinceId: "6",
    countyId: "96",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "high",
    lastContact: "1403/06/30",
    nextStep: "بازنگری نقشه چاه",
    estimatedValue: "5.6 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "10",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1.6",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "35",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1031,
    visitDate: "1403/06/28",
    visitCoordinationPhone: "021-22041370",
    referenceNumber: "RN-1403-031",
    projectName: "مرکز خرید پامچال",
    projectExpertise: "واحد مناقصات",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "پامچال تجارت",
    requesterName: "آقای طاهری",
    contactNumber: "021-22041370",
    email: "customer1031@atis.example",
    projectAddress: "یزد، بلوار دانشجو، مرکز خرید پامچال",
    provinceId: "22",
    countyId: "384",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 3",
    status: "proposalSent",
    priority: "medium",
    lastContact: "1403/06/28",
    nextStep: "پیگیری قرارداد",
    estimatedValue: "2.8 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "4",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "1.75",
    capacity: "8 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "36",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1032,
    visitDate: "1403/06/25",
    visitCoordinationPhone: "026-22042749",
    referenceNumber: "RN-1403-032",
    projectName: "اسکله خدماتی آفتاب",
    projectExpertise: "واحد فنی",
    reference: "نمایندگی جنوب",
    employerName: "خدمات دریایی آفتاب",
    requesterName: "مهندس کاظمی",
    contactNumber: "026-22042749",
    email: "customer1032@atis.example",
    projectAddress: "بندر لنگه، اسکله خدماتی آفتاب",
    provinceId: "23",
    countyId: "394",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "urgent",
    lastContact: "1403/06/25",
    nextStep: "بررسی شرایط محیطی",
    estimatedValue: "2.4 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "3",
    elevatorType: "گیربکس",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "دریایی",
    elevatorSpeed: "0.63",
    capacity: "10 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "37",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1033,
    visitDate: "1403/06/22",
    visitCoordinationPhone: "051-22044128",
    referenceNumber: "RN-1403-033",
    projectName: "مجتمع مسکونی شبنم",
    projectExpertise: "واحد فروش و فنی",
    reference: "اینستاگرام",
    employerName: "شبنم سازه",
    requesterName: "خانم نیک‌فر",
    contactNumber: "051-22044128",
    email: "customer1033@atis.example",
    projectAddress: "تهران، پونک، مجتمع شبنم",
    provinceId: "24",
    countyId: "405",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "medium",
    lastContact: "1403/06/22",
    nextStep: "ارسال مشخصات کابین",
    estimatedValue: "2.7 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "6",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1",
    capacity: "13 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "38",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1034,
    visitDate: "1403/06/20",
    visitCoordinationPhone: "031-22045507",
    referenceNumber: "RN-1403-034",
    projectName: "مرکز آموزشی دانا",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "موسسه دانا",
    requesterName: "آقای سهرابی",
    contactNumber: "031-22045507",
    email: "customer1034@atis.example",
    projectAddress: "رشت، خیابان معلم، مرکز آموزشی دانا",
    provinceId: "2",
    countyId: "17",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "negotiating",
    priority: "low",
    lastContact: "1403/06/20",
    nextStep: "هماهنگی بازدید",
    estimatedValue: "1.8 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "4",
    elevatorType: "هیدرولیک",
    usageTypes: ["مسافربر"],
    environmentType: "آموزشی",
    elevatorSpeed: "1.6",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "39",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1035,
    visitDate: "1403/06/18",
    visitCoordinationPhone: "071-22046886",
    referenceNumber: "RN-1403-035",
    projectName: "مجتمع فردوس",
    projectExpertise: "واحد مناقصات",
    reference: "معرفی مشتری قبلی",
    employerName: "گروه ساختمانی فردوس",
    requesterName: "مهندس امینی",
    contactNumber: "071-22046886",
    email: "customer1035@atis.example",
    projectAddress: "تهران، شهرک غرب، مجتمع فردوس",
    provinceId: "24",
    countyId: "408",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "high",
    lastContact: "1403/06/18",
    nextStep: "برآورد نهایی قیمت",
    estimatedValue: "9.8 میلیارد تومان",
    numberOfUnits: "3",
    numberOfStops: "18",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1.75",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "40",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1036,
    visitDate: "1403/06/15",
    visitCoordinationPhone: "041-22048265",
    referenceNumber: "RN-1403-036",
    projectName: "برج ساحلی صدف",
    projectExpertise: "واحد فنی",
    reference: "نمایندگی جنوب",
    employerName: "صدف کیش",
    requesterName: "آقای راد",
    contactNumber: "041-22048265",
    email: "customer1036@atis.example",
    projectAddress: "قشم، بلوار دریا، برج صدف",
    provinceId: "23",
    countyId: "395",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "high",
    lastContact: "1403/06/15",
    nextStep: "پیگیری امضای قرارداد",
    estimatedValue: "6.6 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "9",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "0.63",
    capacity: "8 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "41",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1037,
    visitDate: "1403/07/12",
    visitCoordinationPhone: "061-22049644",
    referenceNumber: "RN-1403-037",
    projectName: "مرکز پخش سلامت",
    projectExpertise: "واحد فروش و فنی",
    reference: "تماس تلفنی",
    employerName: "پخش سلامت",
    requesterName: "خانم هاشمی",
    contactNumber: "061-22049644",
    email: "customer1037@atis.example",
    projectAddress: "اصفهان، شهرک صنعتی جی، مرکز پخش",
    provinceId: "11",
    countyId: "236",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 1",
    status: "new",
    priority: "medium",
    lastContact: "1403/07/12",
    nextStep: "نیازسنجی فنی",
    estimatedValue: "1.5 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "2",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "انبار",
    elevatorSpeed: "1",
    capacity: "10 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "24",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1038,
    visitDate: "1403/07/10",
    visitCoordinationPhone: "011-22051023",
    referenceNumber: "RN-1403-038",
    projectName: "ساختمان اداری بارمان",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "بارمان توسعه",
    requesterName: "مهندس حبیبی",
    contactNumber: "011-22051023",
    email: "customer1038@atis.example",
    projectAddress: "کرج، مهرشهر، ساختمان بارمان",
    provinceId: "31",
    countyId: "478",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "needsFollowUp",
    priority: "medium",
    lastContact: "1403/07/10",
    nextStep: "تکمیل اطلاعات چاه",
    estimatedValue: "2.8 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "7",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "1.6",
    capacity: "13 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "25",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1039,
    visitDate: "1403/07/08",
    visitCoordinationPhone: "076-22052402",
    referenceNumber: "RN-1403-039",
    projectName: "پروژه مسکونی پارسه",
    projectExpertise: "واحد مناقصات",
    reference: "همکاری معمار",
    employerName: "پارسه سازان",
    requesterName: "آقای رفیعی",
    contactNumber: "076-22052402",
    email: "customer1039@atis.example",
    projectAddress: "شیراز، فرهنگ‌شهر، پروژه پارسه",
    provinceId: "8",
    countyId: "145",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "high",
    lastContact: "1403/07/08",
    nextStep: "بررسی قرارداد اولیه",
    estimatedValue: "7.1 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "15",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "1.75",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "26",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1040,
    visitDate: "1403/07/05",
    visitCoordinationPhone: "025-22053781",
    referenceNumber: "RN-1403-040",
    projectName: "بیمارستان آریانا",
    projectExpertise: "واحد فنی",
    reference: "مناقصه",
    employerName: "بیمارستان آریانا",
    requesterName: "واحد تجهیزات",
    contactNumber: "025-22053781",
    email: "customer1040@atis.example",
    projectAddress: "تهران، پاسداران، بیمارستان آریانا",
    provinceId: "24",
    countyId: "405",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "urgent",
    lastContact: "1403/07/05",
    nextStep: "ارسال پاسخ استعلام",
    estimatedValue: "13.2 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "11",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["بیمارستانی تخت‌بر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "0.63",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "27",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1041,
    visitDate: "1403/07/03",
    visitCoordinationPhone: "021-22055160",
    referenceNumber: "RN-1403-041",
    projectName: "سردخانه نگین",
    projectExpertise: "واحد فروش و فنی",
    reference: "وب‌سایت",
    employerName: "صنایع نگین سرد",
    requesterName: "آقای کمالی",
    contactNumber: "021-22055160",
    email: "customer1041@atis.example",
    projectAddress: "تبریز، شهرک صنعتی غرب، سردخانه نگین",
    provinceId: "4",
    countyId: "53",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 1",
    status: "visited",
    priority: "medium",
    lastContact: "1403/07/03",
    nextStep: "تایید محل نصب",
    estimatedValue: "2.2 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "3",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "صنعتی",
    elevatorSpeed: "1",
    capacity: "8 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "28",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1042,
    visitDate: "1403/06/30",
    visitCoordinationPhone: "026-22056539",
    referenceNumber: "RN-1403-042",
    projectName: "پروژه اداری مهتاب",
    projectExpertise: "واحد فروش",
    reference: "اینستاگرام",
    employerName: "مهتاب عمران",
    requesterName: "خانم تاجیک",
    contactNumber: "026-22056539",
    email: "customer1042@atis.example",
    projectAddress: "قم، پردیسان، پروژه اداری مهتاب",
    provinceId: "26",
    countyId: "433",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 2",
    status: "new",
    priority: "low",
    lastContact: "1403/06/30",
    nextStep: "ارسال بروشور",
    estimatedValue: "2.1 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "5",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "1.6",
    capacity: "10 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "29",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1043,
    visitDate: "1403/06/28",
    visitCoordinationPhone: "051-22057918",
    referenceNumber: "RN-1403-043",
    projectName: "مرکز خرید آرین",
    projectExpertise: "واحد مناقصات",
    reference: "معرفی مشتری قبلی",
    employerName: "گروه آرین تجارت",
    requesterName: "آقای فلاح",
    contactNumber: "051-22057918",
    email: "customer1043@atis.example",
    projectAddress: "بابل، خیابان مدرس، مرکز خرید آرین",
    provinceId: "3",
    countyId: "31",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "medium",
    lastContact: "1403/06/28",
    nextStep: "ارائه پیشنهاد دوم",
    estimatedValue: "3.6 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "6",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "1.75",
    capacity: "13 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "30",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1044,
    visitDate: "1403/06/25",
    visitCoordinationPhone: "031-22059297",
    referenceNumber: "RN-1403-044",
    projectName: "برج نیلوفر",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "نیلوفر سازه",
    requesterName: "مهندس اکبری",
    contactNumber: "031-22059297",
    email: "customer1044@atis.example",
    projectAddress: "قزوین، نادری، برج نیلوفر",
    provinceId: "27",
    countyId: "438",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "visited",
    priority: "high",
    lastContact: "1403/06/25",
    nextStep: "بازدید تکمیلی",
    estimatedValue: "5.3 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "12",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "0.63",
    capacity: "1000 کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "31",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1045,
    visitDate: "1403/06/22",
    visitCoordinationPhone: "071-22060676",
    referenceNumber: "RN-1403-045",
    projectName: "کارخانه رنگ سپید",
    projectExpertise: "واحد فروش و فنی",
    reference: "مناقصه",
    employerName: "رنگ سپید",
    requesterName: "آقای صبوری",
    contactNumber: "071-22060676",
    email: "customer1045@atis.example",
    projectAddress: "اهواز، شهرک صنعتی شماره دو، کارخانه سپید",
    provinceId: "7",
    countyId: "111",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "1403/06/22",
    nextStep: "بررسی ایمنی محیط",
    estimatedValue: "4.4 میلیارد تومان",
    numberOfUnits: "2",
    numberOfStops: "4",
    elevatorType: "گیربکس",
    usageTypes: ["باربر", "ضدانفجار زون"],
    environmentType: "صنعتی",
    elevatorSpeed: "1",
    capacity: "1600 کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "80",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "180",
    shaftDepth: "170",
    shaftHeight: "32",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1046,
    visitDate: "1403/06/20",
    visitCoordinationPhone: "041-22062055",
    referenceNumber: "RN-1403-046",
    projectName: "هتل باغ بهار",
    projectExpertise: "واحد فروش",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "گروه گردشگری بهار",
    requesterName: "خانم علوی",
    contactNumber: "041-22062055",
    email: "customer1046@atis.example",
    projectAddress: "لاهیجان، بلوار امام رضا، هتل باغ بهار",
    provinceId: "2",
    countyId: "23",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 2",
    status: "proposalSent",
    priority: "medium",
    lastContact: "1403/06/20",
    nextStep: "پیگیری تایید نهایی",
    estimatedValue: "3.7 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "7",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "هتل",
    elevatorSpeed: "1.6",
    capacity: "8 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "90",
    doorHeight: "210",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "200",
    shaftDepth: "190",
    shaftHeight: "33",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1047,
    visitDate: "1403/06/18",
    visitCoordinationPhone: "061-22063434",
    referenceNumber: "RN-1403-047",
    projectName: "برج اداری آتیه",
    projectExpertise: "واحد مناقصات",
    reference: "همکاری معمار",
    employerName: "سرمایه‌گذاری آتیه",
    requesterName: "آقای فرهمند",
    contactNumber: "061-22063434",
    email: "customer1047@atis.example",
    projectAddress: "تهران، خیابان مطهری، برج آتیه",
    provinceId: "24",
    countyId: "405",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "urgent",
    lastContact: "1403/06/18",
    nextStep: "جلسه با هیئت مدیره",
    estimatedValue: "18.6 میلیارد تومان",
    numberOfUnits: "5",
    numberOfStops: "20",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "1.75",
    capacity: "10 نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "100",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "220",
    shaftDepth: "210",
    shaftHeight: "34",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1048,
    visitDate: "1403/06/15",
    visitCoordinationPhone: "011-22064813",
    referenceNumber: "RN-1403-048",
    projectName: "مجتمع مهرگان",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "تعاونی مهرگان",
    requesterName: "خانم نظری",
    contactNumber: "011-22064813",
    email: "customer1048@atis.example",
    projectAddress: "اصفهان، سپاهان‌شهر، مجتمع مهرگان",
    provinceId: "11",
    countyId: "236",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "medium",
    lastContact: "1403/06/15",
    nextStep: "بررسی نیاز اولیه",
    estimatedValue: "2.9 میلیارد تومان",
    numberOfUnits: "1",
    numberOfStops: "6",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "0.63",
    capacity: "13 نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "110",
    doorHeight: "210",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "240",
    shaftDepth: "230",
    shaftHeight: "35",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
];
