import { type CustomerRecord } from "@/modules/crm/types/customer.types";

export const emptyCustomerFormValues: Omit<CustomerRecord, "id"> = {
  visitDate: "۱۴۰۳/۰۷/۱۲",
  visitCoordinationPhone: "",
  referenceNumber: "",
  projectName: "",
  projectExpertise: "",
  reference: "",
  employerName: "",
  requesterName: "",
  contactNumber: "",
  email: "",
  projectAddress: "",
  provinceId: "",
  countyId: "",
  source: "",
  salesExpert: "",
  status: "new",
  priority: "medium",
  lastContact: "",
  nextStep: "",
  estimatedValue: "",
  numberOfUnits: "",
  numberOfStops: "",
  elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
  usageTypes: [],
  environmentType: "",
  elevatorSpeed: "",
  capacity: "",
  doorType: "تمام اتوماتیک",
  doorOpeningType: "سانترال",
  floorDoorArrangement: "تک درب",
  doorWidth: "",
  doorHeight: "",
  doorStainlessSteelType: "",
  shaftIronwork: "ندارد",
  foundationIntrusionIntoShaft: "خیر",
  isShaftSuspended: "خیر",
  canPitBeDemolished: "خیر",
  isShaftSurroundingOpen: "خیر",
  shaftSurroundingCoveringTypes: [],
  shaftWidth: "",
  shaftDepth: "",
  shaftHeight: "",
  pitHeightWithoutFlooring: "",
  overheadWithoutFlooring: "",
  travelLength: "",
  requestedPackageType: "",
  description: "",
};

export const defaultCustomers: CustomerRecord[] = [
  {
    ...emptyCustomerFormValues,
    id: 1001,
    visitDate: "۱۴۰۳/۰۷/۱۲",
    visitCoordinationPhone: "۰۲۱-22000000",
    referenceNumber: "RN-1403-001",
    projectName: "برج سپهر",
    projectExpertise: "واحد فروش و فنی",
    reference: "وب‌سایت",
    employerName: "شرکت عمران سپهر",
    requesterName: "مهندس رضایی",
    contactNumber: "۰۲۱-22000000",
    email: "customer1001@atis.example",
    projectAddress: "تهران، خیابان ولیعصر، برج سپهر",
    provinceId: "24",
    countyId: "405",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 1",
    status: "negotiating",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۱۲",
    nextStep: "ارسال پیش‌فاکتور",
    estimatedValue: "۴.۸ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۲",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱",
    capacity: "۸ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "24",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1002,
    visitDate: "۱۴۰۳/۰۷/۱۰",
    visitCoordinationPhone: "۰۲۶-22001379",
    referenceNumber: "RN-1403-002",
    projectName: "مجتمع نگین",
    projectExpertise: "واحد فروش",
    reference: "معرفی مشتری قبلی",
    employerName: "مجتمع تجاری نگین",
    requesterName: "خانم احمدی",
    contactNumber: "۰۲۶-22001379",
    email: "customer1002@atis.example",
    projectAddress: "البرز، بلوار اصلی، مجتمع نگین",
    provinceId: "31",
    countyId: "478",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۱۰",
    nextStep: "ثبت گزارش بازدید",
    estimatedValue: "۳.۲ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۸",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۱.۶",
    capacity: "۱۰ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "25",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1003,
    visitDate: "۱۴۰۳/۰۷/۰۸",
    visitCoordinationPhone: "۰۵۱-22002758",
    referenceNumber: "RN-1403-003",
    projectName: "بخش توسعه بیمارستان آتیه",
    projectExpertise: "واحد مناقصات",
    reference: "مناقصه",
    employerName: "بیمارستان آتیه",
    requesterName: "واحد تدارکات",
    contactNumber: "۰۵۱-22002758",
    email: "customer1003@atis.example",
    projectAddress: "تهران، شهرک غرب، بیمارستان آتیه",
    provinceId: "24",
    countyId: "408",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 3",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۷/۰۸",
    nextStep: "هماهنگی بازدید فنی",
    estimatedValue: "۶.۱ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۸",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["بیمارستانی تخت‌بر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۳ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "26",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1004,
    visitDate: "۱۴۰۳/۰۷/۰۵",
    visitCoordinationPhone: "۰۳۱-22004137",
    referenceNumber: "RN-1403-004",
    projectName: "هتل آرامیس",
    projectExpertise: "واحد فنی",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "گروه هتل‌های آرامیس",
    requesterName: "مهندس کریمی",
    contactNumber: "۰۳۱-22004137",
    email: "customer1004@atis.example",
    projectAddress: "مشهد، بلوار وکیل‌آباد، هتل آرامیس",
    provinceId: "10",
    countyId: "209",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۰۵",
    nextStep: "پیگیری تایید مالی",
    estimatedValue: "۹.۵ میلیارد تومان",
    numberOfUnits: "۳",
    numberOfStops: "۱۴",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "هتل",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "27",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1005,
    visitDate: "۱۴۰۳/۰۷/۰۳",
    visitCoordinationPhone: "۰۷۱-22005516",
    referenceNumber: "RN-1403-005",
    projectName: "برج پزشکان یاس",
    projectExpertise: "واحد فروش و فنی",
    reference: "تماس تلفنی",
    employerName: "تعاونی پزشکان یاس",
    requesterName: "دکتر پارسا",
    contactNumber: "۰۷۱-22005516",
    email: "customer1005@atis.example",
    projectAddress: "اصفهان، خیابان چهارباغ، برج پزشکان",
    provinceId: "11",
    countyId: "236",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 1",
    status: "negotiating",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۰۳",
    nextStep: "بازبینی نقشه چاه",
    estimatedValue: "۵.۴ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۰",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "۱",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "28",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1006,
    visitDate: "۱۴۰۳/۰۶/۳۰",
    visitCoordinationPhone: "۰۴۱-22006895",
    referenceNumber: "RN-1403-006",
    projectName: "سوله صنعتی آذر",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "شرکت صنعت آذر",
    requesterName: "آقای نادری",
    contactNumber: "۰۴۱-22006895",
    email: "customer1006@atis.example",
    projectAddress: "تبریز، شهرک صنعتی، سوله آذر",
    provinceId: "4",
    countyId: "53",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "new",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۳۰",
    nextStep: "تماس اولیه",
    estimatedValue: "۲.۱ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۳",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "صنعتی",
    elevatorSpeed: "۱.۶",
    capacity: "۸ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "29",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1007,
    visitDate: "۱۴۰۳/۰۶/۲۸",
    visitCoordinationPhone: "۰۶۱-22008274",
    referenceNumber: "RN-1403-007",
    projectName: "مرکز خرید ساحل",
    projectExpertise: "واحد مناقصات",
    reference: "نمایندگی جنوب",
    employerName: "شرکت توسعه ساحل",
    requesterName: "خانم صفایی",
    contactNumber: "۰۶۱-22008274",
    email: "customer1007@atis.example",
    projectAddress: "بندر عباس، بلوار ساحلی، مرکز خرید ساحل",
    provinceId: "23",
    countyId: "393",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۶/۲۸",
    nextStep: "ارسال طرح فنی",
    estimatedValue: "۸.۷ میلیارد تومان",
    numberOfUnits: "۴",
    numberOfStops: "۶",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۰ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "30",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1008,
    visitDate: "۱۴۰۳/۰۶/۲۵",
    visitCoordinationPhone: "۰۱۱-22009653",
    referenceNumber: "RN-1403-008",
    projectName: "مجتمع مسکونی باران",
    projectExpertise: "واحد فنی",
    reference: "اینستاگرام",
    employerName: "انبوه‌سازان باران",
    requesterName: "مهندس نوری",
    contactNumber: "۰۱۱-22009653",
    email: "customer1008@atis.example",
    projectAddress: "رشت، گلسار، مجتمع باران",
    provinceId: "2",
    countyId: "17",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 4",
    status: "needsFollowUp",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۲۵",
    nextStep: "هماهنگی جلسه حضوری",
    estimatedValue: "۳.۹ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۷",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۳ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "31",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1009,
    visitDate: "۱۴۰۳/۰۶/۲۲",
    visitCoordinationPhone: "۰۷۶-22011032",
    referenceNumber: "RN-1403-009",
    projectName: "پردیس اداری نیایش",
    projectExpertise: "واحد فروش و فنی",
    reference: "همکاری معمار",
    employerName: "شرکت پردیس نیایش",
    requesterName: "آقای صادقی",
    contactNumber: "۰۷۶-22011032",
    email: "customer1009@atis.example",
    projectAddress: "تهران، بزرگراه نیایش، پردیس اداری",
    provinceId: "24",
    countyId: "405",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 1",
    status: "proposalSent",
    priority: "high",
    lastContact: "۱۴۰۳/۰۶/۲۲",
    nextStep: "دریافت نظر مشاور",
    estimatedValue: "۱۲.۴ میلیارد تومان",
    numberOfUnits: "۴",
    numberOfStops: "۱۶",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "۱",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "32",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1010,
    visitDate: "۱۴۰۳/۰۶/۲۰",
    visitCoordinationPhone: "۰۲۵-22012411",
    referenceNumber: "RN-1403-010",
    projectName: "کلینیک مهر",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "کلینیک تخصصی مهر",
    requesterName: "خانم رستمی",
    contactNumber: "۰۲۵-22012411",
    email: "customer1010@atis.example",
    projectAddress: "شیراز، معالی‌آباد، کلینیک مهر",
    provinceId: "8",
    countyId: "145",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "negotiating",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۲۰",
    nextStep: "ارسال لیست تجهیزات",
    estimatedValue: "۲.۷ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۵",
    elevatorType: "هیدرولیک",
    usageTypes: ["برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "۱.۶",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "33",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1011,
    visitDate: "۱۴۰۳/۰۶/۱۸",
    visitCoordinationPhone: "۰۲۱-22013790",
    referenceNumber: "RN-1403-011",
    projectName: "انبار مرکزی پارس",
    projectExpertise: "واحد مناقصات",
    reference: "تماس تلفنی",
    employerName: "پخش پارس",
    requesterName: "آقای مولایی",
    contactNumber: "۰۲۱-22013790",
    email: "customer1011@atis.example",
    projectAddress: "قم، شهرک صنعتی شکوهیه، انبار مرکزی",
    provinceId: "26",
    countyId: "433",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "low",
    lastContact: "۱۴۰۳/۰۶/۱۸",
    nextStep: "ثبت ابعاد نهایی",
    estimatedValue: "۱.۶ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۲",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "انبار",
    elevatorSpeed: "۱.۷۵",
    capacity: "۸ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "34",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1012,
    visitDate: "۱۴۰۳/۰۶/۱۵",
    visitCoordinationPhone: "۰۲۶-22015169",
    referenceNumber: "RN-1403-012",
    projectName: "برج نارنجستان",
    projectExpertise: "واحد فنی",
    reference: "معرفی مشتری قبلی",
    employerName: "شرکت نارنجستان",
    requesterName: "مهندس محمودی",
    contactNumber: "۰۲۶-22015169",
    email: "customer1012@atis.example",
    projectAddress: "ساری، بلوار پاسداران، برج نارنجستان",
    provinceId: "3",
    countyId: "35",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "high",
    lastContact: "۱۴۰۳/۰۶/۱۵",
    nextStep: "بررسی اولیه نقشه",
    estimatedValue: "۵.۹ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۱",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۰ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "35",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1013,
    visitDate: "۱۴۰۳/۰۷/۱۲",
    visitCoordinationPhone: "۰۵۱-22016548",
    referenceNumber: "RN-1403-013",
    projectName: "پروژه تجاری زیتون",
    projectExpertise: "واحد فروش و فنی",
    reference: "مناقصه",
    employerName: "سرمایه‌گذاری زیتون",
    requesterName: "خانم حیدری",
    contactNumber: "۰۵۱-22016548",
    email: "customer1013@atis.example",
    projectAddress: "اهواز، کیانپارس، پروژه زیتون",
    provinceId: "7",
    countyId: "111",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۷/۱۲",
    nextStep: "تکمیل اسناد مناقصه",
    estimatedValue: "۷.۸ میلیارد تومان",
    numberOfUnits: "۳",
    numberOfStops: "۹",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۱",
    capacity: "۱۳ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "36",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1014,
    visitDate: "۱۴۰۳/۰۷/۱۰",
    visitCoordinationPhone: "۰۳۱-22017927",
    referenceNumber: "RN-1403-014",
    projectName: "مجتمع اقامتی کوهستان",
    projectExpertise: "واحد فروش",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "گروه گردشگری کوهستان",
    requesterName: "آقای حاتمی",
    contactNumber: "۰۳۱-22017927",
    email: "customer1014@atis.example",
    projectAddress: "کرمانشاه، طاق‌بستان، مجتمع اقامتی",
    provinceId: "6",
    countyId: "96",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 2",
    status: "proposalSent",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۱۰",
    nextStep: "انتظار تایید هیئت مدیره",
    estimatedValue: "۴.۳ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۶",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "هتل",
    elevatorSpeed: "۱.۶",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "37",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1015,
    visitDate: "۱۴۰۳/۰۷/۰۸",
    visitCoordinationPhone: "۰۷۱-22019306",
    referenceNumber: "RN-1403-015",
    projectName: "پروژه مسکن آفتاب",
    projectExpertise: "واحد مناقصات",
    reference: "وب‌سایت",
    employerName: "تعاونی مسکن آفتاب",
    requesterName: "مهندس شمس",
    contactNumber: "۰۷۱-22019306",
    email: "customer1015@atis.example",
    projectAddress: "یزد، صفاییه، پروژه آفتاب",
    provinceId: "22",
    countyId: "384",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۰۸",
    nextStep: "اصلاح جانمایی درب",
    estimatedValue: "۶.۲ میلیارد تومان",
    numberOfUnits: "۳",
    numberOfStops: "۹",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "38",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1016,
    visitDate: "۱۴۰۳/۰۷/۰۵",
    visitCoordinationPhone: "۰۴۱-22020685",
    referenceNumber: "RN-1403-016",
    projectName: "کارخانه بسته‌بندی خلیج",
    projectExpertise: "واحد فنی",
    reference: "نمایندگی جنوب",
    employerName: "صنایع غذایی خلیج",
    requesterName: "آقای امیری",
    contactNumber: "۰۴۱-22020685",
    email: "customer1016@atis.example",
    projectAddress: "بوشهر، شهرک صنعتی، کارخانه خلیج",
    provinceId: "19",
    countyId: "354",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 4",
    status: "negotiating",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۰۵",
    nextStep: "بازدید دوم فنی",
    estimatedValue: "۳.۵ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۴",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "صنعتی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۸ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "39",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1017,
    visitDate: "۱۴۰۳/۰۷/۰۳",
    visitCoordinationPhone: "۰۶۱-22022064",
    referenceNumber: "RN-1403-017",
    projectName: "برج آسمان",
    projectExpertise: "واحد فروش و فنی",
    reference: "اینستاگرام",
    employerName: "گروه ساختمانی آسمان",
    requesterName: "خانم یوسفی",
    contactNumber: "۰۶۱-22022064",
    email: "customer1017@atis.example",
    projectAddress: "قزوین، بلوار دانشگاه، برج آسمان",
    provinceId: "27",
    countyId: "438",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 1",
    status: "new",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۰۳",
    nextStep: "تماس جهت نیازسنجی",
    estimatedValue: "۵.۱ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۳",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱",
    capacity: "۱۰ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "40",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1018,
    visitDate: "۱۴۰۳/۰۶/۳۰",
    visitCoordinationPhone: "۰۱۱-22023443",
    referenceNumber: "RN-1403-018",
    projectName: "مرکز لجستیک شرق",
    projectExpertise: "واحد فروش",
    reference: "تماس تلفنی",
    employerName: "لجستیک شرق",
    requesterName: "آقای توسلی",
    contactNumber: "۰۱۱-22023443",
    email: "customer1018@atis.example",
    projectAddress: "مشهد، جاده سرخس، مرکز لجستیک",
    provinceId: "10",
    countyId: "209",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "low",
    lastContact: "۱۴۰۳/۰۶/۳۰",
    nextStep: "ارسال گزارش ابعاد",
    estimatedValue: "۱.۹ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۲",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "انبار",
    elevatorSpeed: "۱.۶",
    capacity: "۱۳ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "41",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1019,
    visitDate: "۱۴۰۳/۰۶/۲۸",
    visitCoordinationPhone: "۰۷۶-22024822",
    referenceNumber: "RN-1403-019",
    projectName: "ساختمان اداری دیبا",
    projectExpertise: "واحد مناقصات",
    reference: "همکاری معمار",
    employerName: "شرکت دیبا سازه",
    requesterName: "مهندس دادگر",
    contactNumber: "۰۷۶-22024822",
    email: "customer1019@atis.example",
    projectAddress: "تهران، سعادت‌آباد، ساختمان دیبا",
    provinceId: "24",
    countyId: "405",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "high",
    lastContact: "۱۴۰۳/۰۶/۲۸",
    nextStep: "دریافت تایید کارفرما",
    estimatedValue: "۳.۴ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۷",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "24",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1020,
    visitDate: "۱۴۰۳/۰۶/۲۵",
    visitCoordinationPhone: "۰۲۵-22026201",
    referenceNumber: "RN-1403-020",
    projectName: "بازارچه اطلس",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "شرکت اطلس بازار",
    requesterName: "خانم فراهانی",
    contactNumber: "۰۲۵-22026201",
    email: "customer1020@atis.example",
    projectAddress: "کرج، عظیمیه، بازارچه اطلس",
    provinceId: "31",
    countyId: "478",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۲۵",
    nextStep: "پیگیری پیش‌پرداخت",
    estimatedValue: "۳.۱ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۵",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "25",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1021,
    visitDate: "۱۴۰۳/۰۶/۲۲",
    visitCoordinationPhone: "۰۲۱-22027580",
    referenceNumber: "RN-1403-021",
    projectName: "بیمارستان سلامت شمال",
    projectExpertise: "واحد فروش و فنی",
    reference: "مناقصه",
    employerName: "بیمارستان سلامت",
    requesterName: "واحد فنی",
    contactNumber: "۰۲۱-22027580",
    email: "customer1021@atis.example",
    projectAddress: "رشت، بلوار نماز، بیمارستان سلامت",
    provinceId: "2",
    countyId: "17",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۶/۲۲",
    nextStep: "تکمیل مدارک فنی",
    estimatedValue: "۱۰.۲ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۰",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["بیمارستانی تخت‌بر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "۱",
    capacity: "۸ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "26",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1022,
    visitDate: "۱۴۰۳/۰۶/۲۰",
    visitCoordinationPhone: "۰۲۶-22028959",
    referenceNumber: "RN-1403-022",
    projectName: "مجتمع ویلایی سرو",
    projectExpertise: "واحد فروش",
    reference: "اینستاگرام",
    employerName: "شرکت سرو شمال",
    requesterName: "آقای بهشتی",
    contactNumber: "۰۲۶-22028959",
    email: "customer1022@atis.example",
    projectAddress: "نور، جاده ساحلی، مجتمع سرو",
    provinceId: "3",
    countyId: "38",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 2",
    status: "new",
    priority: "low",
    lastContact: "۱۴۰۳/۰۶/۲۰",
    nextStep: "ارسال کاتالوگ",
    estimatedValue: "۱.۴ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۳",
    elevatorType: "هیدرولیک",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱.۶",
    capacity: "۱۰ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "27",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1023,
    visitDate: "۱۴۰۳/۰۶/۱۸",
    visitCoordinationPhone: "۰۵۱-22030338",
    referenceNumber: "RN-1403-023",
    projectName: "پالایشگاه نمونه",
    projectExpertise: "واحد مناقصات",
    reference: "مناقصه",
    employerName: "مهندسی انرژی نمونه",
    requesterName: "مهندس سلیمانی",
    contactNumber: "۰۵۱-22030338",
    email: "customer1023@atis.example",
    projectAddress: "عسلویه، سایت صنعتی، پالایشگاه نمونه",
    provinceId: "19",
    countyId: "363",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۶/۱۸",
    nextStep: "بررسی الزامات ضدانفجار",
    estimatedValue: "۸.۹ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۵",
    elevatorType: "گیربکس",
    usageTypes: ["صنعتی آی‌پی", "ضدانفجار زون"],
    environmentType: "صنعتی",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۳ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "28",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1024,
    visitDate: "۱۴۰۳/۰۶/۱۵",
    visitCoordinationPhone: "۰۳۱-22031717",
    referenceNumber: "RN-1403-024",
    projectName: "دانشکده فنی آینده",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "دانشگاه آینده",
    requesterName: "خانم کیانی",
    contactNumber: "۰۳۱-22031717",
    email: "customer1024@atis.example",
    projectAddress: "اصفهان، دانشگاه آینده، دانشکده فنی",
    provinceId: "11",
    countyId: "236",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "negotiating",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۱۵",
    nextStep: "تنظیم جلسه با مشاور",
    estimatedValue: "۲.۶ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۴",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "آموزشی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "29",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1025,
    visitDate: "۱۴۰۳/۰۷/۱۲",
    visitCoordinationPhone: "۰۷۱-22033096",
    referenceNumber: "RN-1403-025",
    projectName: "مرکز درمانی امید",
    projectExpertise: "واحد فروش و فنی",
    reference: "معرفی مشتری قبلی",
    employerName: "مرکز درمانی امید",
    requesterName: "دکتر عظیمی",
    contactNumber: "۰۷۱-22033096",
    email: "customer1025@atis.example",
    projectAddress: "تبریز، ولیعصر، مرکز درمانی امید",
    provinceId: "4",
    countyId: "53",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 1",
    status: "proposalSent",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۱۲",
    nextStep: "پیگیری تاییدیه فنی",
    estimatedValue: "۴.۹ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۷",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "۱",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "30",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1026,
    visitDate: "۱۴۰۳/۰۷/۱۰",
    visitCoordinationPhone: "۰۴۱-22034475",
    referenceNumber: "RN-1403-026",
    projectName: "برج مسکونی آریا",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "آریا سازه",
    requesterName: "مهندس لطیفی",
    contactNumber: "۰۴۱-22034475",
    email: "customer1026@atis.example",
    projectAddress: "شیراز، قصردشت، برج آریا",
    provinceId: "8",
    countyId: "145",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۱۰",
    nextStep: "ثبت گزارش بازدید",
    estimatedValue: "۵.۷ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۲",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱.۶",
    capacity: "۸ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "31",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1027,
    visitDate: "۱۴۰۳/۰۷/۰۸",
    visitCoordinationPhone: "۰۶۱-22035854",
    referenceNumber: "RN-1403-027",
    projectName: "پاساژ مینا",
    projectExpertise: "واحد مناقصات",
    reference: "تماس تلفنی",
    employerName: "سرمایه‌گذاری مینا",
    requesterName: "خانم سلطانی",
    contactNumber: "۰۶۱-22035854",
    email: "customer1027@atis.example",
    projectAddress: "قم، خیابان جمهوری، پاساژ مینا",
    provinceId: "26",
    countyId: "433",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 3",
    status: "needsFollowUp",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۰۸",
    nextStep: "ارسال نسخه اصلاحی پیشنهاد",
    estimatedValue: "۳.۸ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۶",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۰ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "32",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1028,
    visitDate: "۱۴۰۳/۰۷/۰۵",
    visitCoordinationPhone: "۰۱۱-22037233",
    referenceNumber: "RN-1403-028",
    projectName: "ساختمان ستاره شرق",
    projectExpertise: "واحد فنی",
    reference: "اینستاگرام",
    employerName: "ستاره شرق",
    requesterName: "آقای مرادی",
    contactNumber: "۰۱۱-22037233",
    email: "customer1028@atis.example",
    projectAddress: "نیشابور، بلوار بعثت، ساختمان ستاره شرق",
    provinceId: "10",
    countyId: "210",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۰۵",
    nextStep: "تماس اولیه",
    estimatedValue: "۲.۹ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۸",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۳ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "33",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1029,
    visitDate: "۱۴۰۳/۰۷/۰۳",
    visitCoordinationPhone: "۰۷۶-22038612",
    referenceNumber: "RN-1403-029",
    projectName: "کارگاه قطعات دقیق",
    projectExpertise: "واحد فروش و فنی",
    reference: "وب‌سایت",
    employerName: "قطعات دقیق البرز",
    requesterName: "مهندس جمشیدی",
    contactNumber: "۰۷۶-22038612",
    email: "customer1029@atis.example",
    projectAddress: "فردیس، شهرک صنعتی، کارگاه قطعات دقیق",
    provinceId: "31",
    countyId: "483",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 1",
    status: "negotiating",
    priority: "low",
    lastContact: "۱۴۰۳/۰۷/۰۳",
    nextStep: "نهایی کردن ظرفیت",
    estimatedValue: "۱.۲ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۲",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "صنعتی",
    elevatorSpeed: "۱",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "34",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1030,
    visitDate: "۱۴۰۳/۰۶/۳۰",
    visitCoordinationPhone: "۰۲۵-22039991",
    referenceNumber: "RN-1403-030",
    projectName: "پروژه اطلس غرب",
    projectExpertise: "واحد فروش",
    reference: "همکاری معمار",
    employerName: "اطلس غرب ایرانیان",
    requesterName: "خانم صابری",
    contactNumber: "۰۲۵-22039991",
    email: "customer1030@atis.example",
    projectAddress: "کرمانشاه، الهیه، پروژه اطلس غرب",
    provinceId: "6",
    countyId: "96",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 2",
    status: "visited",
    priority: "high",
    lastContact: "۱۴۰۳/۰۶/۳۰",
    nextStep: "بازنگری نقشه چاه",
    estimatedValue: "۵.۶ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۰",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱.۶",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "35",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1031,
    visitDate: "۱۴۰۳/۰۶/۲۸",
    visitCoordinationPhone: "۰۲۱-22041370",
    referenceNumber: "RN-1403-031",
    projectName: "مرکز خرید پامچال",
    projectExpertise: "واحد مناقصات",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "پامچال تجارت",
    requesterName: "آقای طاهری",
    contactNumber: "۰۲۱-22041370",
    email: "customer1031@atis.example",
    projectAddress: "یزد، بلوار دانشجو، مرکز خرید پامچال",
    provinceId: "22",
    countyId: "384",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 3",
    status: "proposalSent",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۲۸",
    nextStep: "پیگیری قرارداد",
    estimatedValue: "۲.۸ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۴",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۱.۷۵",
    capacity: "۸ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "36",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1032,
    visitDate: "۱۴۰۳/۰۶/۲۵",
    visitCoordinationPhone: "۰۲۶-22042749",
    referenceNumber: "RN-1403-032",
    projectName: "اسکله خدماتی آفتاب",
    projectExpertise: "واحد فنی",
    reference: "نمایندگی جنوب",
    employerName: "خدمات دریایی آفتاب",
    requesterName: "مهندس کاظمی",
    contactNumber: "۰۲۶-22042749",
    email: "customer1032@atis.example",
    projectAddress: "بندر لنگه، اسکله خدماتی آفتاب",
    provinceId: "23",
    countyId: "394",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۶/۲۵",
    nextStep: "بررسی شرایط محیطی",
    estimatedValue: "۲.۴ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۳",
    elevatorType: "گیربکس",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "دریایی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۰ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "37",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1033,
    visitDate: "۱۴۰۳/۰۶/۲۲",
    visitCoordinationPhone: "۰۵۱-22044128",
    referenceNumber: "RN-1403-033",
    projectName: "مجتمع مسکونی شبنم",
    projectExpertise: "واحد فروش و فنی",
    reference: "اینستاگرام",
    employerName: "شبنم سازه",
    requesterName: "خانم نیک‌فر",
    contactNumber: "۰۵۱-22044128",
    email: "customer1033@atis.example",
    projectAddress: "تهران، پونک، مجتمع شبنم",
    provinceId: "24",
    countyId: "405",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۲۲",
    nextStep: "ارسال مشخصات کابین",
    estimatedValue: "۲.۷ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۶",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱",
    capacity: "۱۳ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "38",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1034,
    visitDate: "۱۴۰۳/۰۶/۲۰",
    visitCoordinationPhone: "۰۳۱-22045507",
    referenceNumber: "RN-1403-034",
    projectName: "مرکز آموزشی دانا",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "موسسه دانا",
    requesterName: "آقای سهرابی",
    contactNumber: "۰۳۱-22045507",
    email: "customer1034@atis.example",
    projectAddress: "رشت، خیابان معلم، مرکز آموزشی دانا",
    provinceId: "2",
    countyId: "17",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "negotiating",
    priority: "low",
    lastContact: "۱۴۰۳/۰۶/۲۰",
    nextStep: "هماهنگی بازدید",
    estimatedValue: "۱.۸ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۴",
    elevatorType: "هیدرولیک",
    usageTypes: ["مسافربر"],
    environmentType: "آموزشی",
    elevatorSpeed: "۱.۶",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "39",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1035,
    visitDate: "۱۴۰۳/۰۶/۱۸",
    visitCoordinationPhone: "۰۷۱-22046886",
    referenceNumber: "RN-1403-035",
    projectName: "مجتمع فردوس",
    projectExpertise: "واحد مناقصات",
    reference: "معرفی مشتری قبلی",
    employerName: "گروه ساختمانی فردوس",
    requesterName: "مهندس امینی",
    contactNumber: "۰۷۱-22046886",
    email: "customer1035@atis.example",
    projectAddress: "تهران، شهرک غرب، مجتمع فردوس",
    provinceId: "24",
    countyId: "408",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 3",
    status: "visited",
    priority: "high",
    lastContact: "۱۴۰۳/۰۶/۱۸",
    nextStep: "برآورد نهایی قیمت",
    estimatedValue: "۹.۸ میلیارد تومان",
    numberOfUnits: "۳",
    numberOfStops: "۱۸",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "40",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1036,
    visitDate: "۱۴۰۳/۰۶/۱۵",
    visitCoordinationPhone: "۰۴۱-22048265",
    referenceNumber: "RN-1403-036",
    projectName: "برج ساحلی صدف",
    projectExpertise: "واحد فنی",
    reference: "نمایندگی جنوب",
    employerName: "صدف کیش",
    requesterName: "آقای راد",
    contactNumber: "۰۴۱-22048265",
    email: "customer1036@atis.example",
    projectAddress: "قشم، بلوار دریا، برج صدف",
    provinceId: "23",
    countyId: "395",
    source: "نمایندگی جنوب",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "high",
    lastContact: "۱۴۰۳/۰۶/۱۵",
    nextStep: "پیگیری امضای قرارداد",
    estimatedValue: "۶.۶ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۹",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۸ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "41",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1037,
    visitDate: "۱۴۰۳/۰۷/۱۲",
    visitCoordinationPhone: "۰۶۱-22049644",
    referenceNumber: "RN-1403-037",
    projectName: "مرکز پخش سلامت",
    projectExpertise: "واحد فروش و فنی",
    reference: "تماس تلفنی",
    employerName: "پخش سلامت",
    requesterName: "خانم هاشمی",
    contactNumber: "۰۶۱-22049644",
    email: "customer1037@atis.example",
    projectAddress: "اصفهان، شهرک صنعتی جی، مرکز پخش",
    provinceId: "11",
    countyId: "236",
    source: "تماس تلفنی",
    salesExpert: "کارشناس فروش 1",
    status: "new",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۱۲",
    nextStep: "نیازسنجی فنی",
    estimatedValue: "۱.۵ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۲",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر"],
    environmentType: "انبار",
    elevatorSpeed: "۱",
    capacity: "۱۰ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "24",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1038,
    visitDate: "۱۴۰۳/۰۷/۱۰",
    visitCoordinationPhone: "۰۱۱-22051023",
    referenceNumber: "RN-1403-038",
    projectName: "ساختمان اداری بارمان",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "بارمان توسعه",
    requesterName: "مهندس حبیبی",
    contactNumber: "۰۱۱-22051023",
    email: "customer1038@atis.example",
    projectAddress: "کرج، مهرشهر، ساختمان بارمان",
    provinceId: "31",
    countyId: "478",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 2",
    status: "needsFollowUp",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۱۰",
    nextStep: "تکمیل اطلاعات چاه",
    estimatedValue: "۲.۸ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۷",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "۱.۶",
    capacity: "۱۳ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "25",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1039,
    visitDate: "۱۴۰۳/۰۷/۰۸",
    visitCoordinationPhone: "۰۷۶-22052402",
    referenceNumber: "RN-1403-039",
    projectName: "پروژه مسکونی پارسه",
    projectExpertise: "واحد مناقصات",
    reference: "همکاری معمار",
    employerName: "پارسه سازان",
    requesterName: "آقای رفیعی",
    contactNumber: "۰۷۶-22052402",
    email: "customer1039@atis.example",
    projectAddress: "شیراز، فرهنگ‌شهر، پروژه پارسه",
    provinceId: "8",
    countyId: "145",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۰۸",
    nextStep: "بررسی قرارداد اولیه",
    estimatedValue: "۷.۱ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۵",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "26",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1040,
    visitDate: "۱۴۰۳/۰۷/۰۵",
    visitCoordinationPhone: "۰۲۵-22053781",
    referenceNumber: "RN-1403-040",
    projectName: "بیمارستان آریانا",
    projectExpertise: "واحد فنی",
    reference: "مناقصه",
    employerName: "بیمارستان آریانا",
    requesterName: "واحد تجهیزات",
    contactNumber: "۰۲۵-22053781",
    email: "customer1040@atis.example",
    projectAddress: "تهران، پاسداران، بیمارستان آریانا",
    provinceId: "24",
    countyId: "405",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 4",
    status: "proposalSent",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۷/۰۵",
    nextStep: "ارسال پاسخ استعلام",
    estimatedValue: "۱۳.۲ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۱",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["بیمارستانی تخت‌بر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "27",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1041,
    visitDate: "۱۴۰۳/۰۷/۰۳",
    visitCoordinationPhone: "۰۲۱-22055160",
    referenceNumber: "RN-1403-041",
    projectName: "سردخانه نگین",
    projectExpertise: "واحد فروش و فنی",
    reference: "وب‌سایت",
    employerName: "صنایع نگین سرد",
    requesterName: "آقای کمالی",
    contactNumber: "۰۲۱-22055160",
    email: "customer1041@atis.example",
    projectAddress: "تبریز، شهرک صنعتی غرب، سردخانه نگین",
    provinceId: "4",
    countyId: "53",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 1",
    status: "visited",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۰۳",
    nextStep: "تایید محل نصب",
    estimatedValue: "۲.۲ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۳",
    elevatorType: "هیدرولیک",
    usageTypes: ["باربر", "صنعتی آی‌پی"],
    environmentType: "صنعتی",
    elevatorSpeed: "۱",
    capacity: "۸ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "28",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1042,
    visitDate: "۱۴۰۳/۰۶/۳۰",
    visitCoordinationPhone: "۰۲۶-22056539",
    referenceNumber: "RN-1403-042",
    projectName: "پروژه اداری مهتاب",
    projectExpertise: "واحد فروش",
    reference: "اینستاگرام",
    employerName: "مهتاب عمران",
    requesterName: "خانم تاجیک",
    contactNumber: "۰۲۶-22056539",
    email: "customer1042@atis.example",
    projectAddress: "قم، پردیسان، پروژه اداری مهتاب",
    provinceId: "26",
    countyId: "433",
    source: "اینستاگرام",
    salesExpert: "کارشناس فروش 2",
    status: "new",
    priority: "low",
    lastContact: "۱۴۰۳/۰۶/۳۰",
    nextStep: "ارسال بروشور",
    estimatedValue: "۲.۱ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۵",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "۱.۶",
    capacity: "۱۰ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "29",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1043,
    visitDate: "۱۴۰۳/۰۶/۲۸",
    visitCoordinationPhone: "۰۵۱-22057918",
    referenceNumber: "RN-1403-043",
    projectName: "مرکز خرید آرین",
    projectExpertise: "واحد مناقصات",
    reference: "معرفی مشتری قبلی",
    employerName: "گروه آرین تجارت",
    requesterName: "آقای فلاح",
    contactNumber: "۰۵۱-22057918",
    email: "customer1043@atis.example",
    projectAddress: "بابل، خیابان مدرس، مرکز خرید آرین",
    provinceId: "3",
    countyId: "31",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۲۸",
    nextStep: "ارائه پیشنهاد دوم",
    estimatedValue: "۳.۶ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۶",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر", "باربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۳ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تک درب",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "30",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1044,
    visitDate: "۱۴۰۳/۰۶/۲۵",
    visitCoordinationPhone: "۰۳۱-22059297",
    referenceNumber: "RN-1403-044",
    projectName: "برج نیلوفر",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "نیلوفر سازه",
    requesterName: "مهندس اکبری",
    contactNumber: "۰۳۱-22059297",
    email: "customer1044@atis.example",
    projectAddress: "قزوین، نادری، برج نیلوفر",
    provinceId: "27",
    countyId: "438",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "visited",
    priority: "high",
    lastContact: "۱۴۰۳/۰۶/۲۵",
    nextStep: "بازدید تکمیلی",
    estimatedValue: "۵.۳ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۲",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۰۰۰ کیلوگرم",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "31",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1045,
    visitDate: "۱۴۰۳/۰۶/۲۲",
    visitCoordinationPhone: "۰۷۱-22060676",
    referenceNumber: "RN-1403-045",
    projectName: "کارخانه رنگ سپید",
    projectExpertise: "واحد فروش و فنی",
    reference: "مناقصه",
    employerName: "رنگ سپید",
    requesterName: "آقای صبوری",
    contactNumber: "۰۷۱-22060676",
    email: "customer1045@atis.example",
    projectAddress: "اهواز، شهرک صنعتی شماره دو، کارخانه سپید",
    provinceId: "7",
    countyId: "111",
    source: "مناقصه",
    salesExpert: "کارشناس فروش 1",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۶/۲۲",
    nextStep: "بررسی ایمنی محیط",
    estimatedValue: "۴.۴ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۴",
    elevatorType: "گیربکس",
    usageTypes: ["باربر", "ضدانفجار زون"],
    environmentType: "صنعتی",
    elevatorSpeed: "۱",
    capacity: "۱۶۰۰ کیلوگرم",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "تونلی",
    doorWidth: "۸۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["سفالی"],
    shaftWidth: "۱۸۰",
    shaftDepth: "۱۷۰",
    shaftHeight: "32",
    requestedPackageType: "پکیج کامل آسانسور",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1046,
    visitDate: "۱۴۰۳/۰۶/۲۰",
    visitCoordinationPhone: "۰۴۱-22062055",
    referenceNumber: "RN-1403-046",
    projectName: "هتل باغ بهار",
    projectExpertise: "واحد فروش",
    reference: "نمایشگاه صنعت ساختمان",
    employerName: "گروه گردشگری بهار",
    requesterName: "خانم علوی",
    contactNumber: "۰۴۱-22062055",
    email: "customer1046@atis.example",
    projectAddress: "لاهیجان، بلوار امام رضا، هتل باغ بهار",
    provinceId: "2",
    countyId: "23",
    source: "نمایشگاه صنعت ساختمان",
    salesExpert: "کارشناس فروش 2",
    status: "proposalSent",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۲۰",
    nextStep: "پیگیری تایید نهایی",
    estimatedValue: "۳.۷ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۷",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "هتل",
    elevatorSpeed: "۱.۶",
    capacity: "۸ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تک درب",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بتنی"],
    shaftWidth: "۲۰۰",
    shaftDepth: "۱۹۰",
    shaftHeight: "33",
    requestedPackageType: "پکیج اقتصادی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1047,
    visitDate: "۱۴۰۳/۰۶/۱۸",
    visitCoordinationPhone: "۰۶۱-22063434",
    referenceNumber: "RN-1403-047",
    projectName: "برج اداری آتیه",
    projectExpertise: "واحد مناقصات",
    reference: "همکاری معمار",
    employerName: "سرمایه‌گذاری آتیه",
    requesterName: "آقای فرهمند",
    contactNumber: "۰۶۱-22063434",
    email: "customer1047@atis.example",
    projectAddress: "تهران، خیابان مطهری، برج آتیه",
    provinceId: "24",
    countyId: "405",
    source: "همکاری معمار",
    salesExpert: "کارشناس فروش 3",
    status: "negotiating",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۶/۱۸",
    nextStep: "جلسه با هیئت مدیره",
    estimatedValue: "۱۸.۶ میلیارد تومان",
    numberOfUnits: "۵",
    numberOfStops: "۲۰",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "اداری",
    elevatorSpeed: "۱.۷۵",
    capacity: "۱۰ نفره",
    doorOpeningType: "سانترال",
    floorDoorArrangement: "دو درب در مجاور",
    doorWidth: "۱۰۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "34",
    requestedPackageType: "پکیج بیمارستانی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
  {
    ...emptyCustomerFormValues,
    id: 1048,
    visitDate: "۱۴۰۳/۰۶/۱۵",
    visitCoordinationPhone: "۰۱۱-22064813",
    referenceNumber: "RN-1403-048",
    projectName: "مجتمع مهرگان",
    projectExpertise: "واحد فنی",
    reference: "وب‌سایت",
    employerName: "تعاونی مهرگان",
    requesterName: "خانم نظری",
    contactNumber: "۰۱۱-22064813",
    email: "customer1048@atis.example",
    projectAddress: "اصفهان، سپاهان‌شهر، مجتمع مهرگان",
    provinceId: "11",
    countyId: "236",
    source: "وب‌سایت",
    salesExpert: "کارشناس فروش 4",
    status: "new",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۶/۱۵",
    nextStep: "بررسی نیاز اولیه",
    estimatedValue: "۲.۹ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۶",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۰.۶۳",
    capacity: "۱۳ نفره",
    doorOpeningType: "چپ/راست",
    floorDoorArrangement: "تونلی",
    doorWidth: "۱۱۰",
    doorHeight: "۲۱۰",
    shaftIronwork: "ندارد",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    shaftWidth: "۲۴۰",
    shaftDepth: "۲۳۰",
    shaftHeight: "35",
    requestedPackageType: "تامین قطعات اصلی",
    description: "داده نمونه برای تست فهرست، فیلتر، صفحه‌بندی و دریافت اکسل.",
  },
];
