import { type CustomerRecord } from "@/modules/crm/types/customer.types";

export const emptyCustomerFormValues: Omit<CustomerRecord, "id"> = {
  visitDate: "۱۴۰۳/۰۷/۱۲",
  visitCoordinationPhone: "",
  referenceNumber: "",
  projectName: "",
  projectExpertise: "",
  reference: "",
  employerName: "",
  requesterName: "",
  contactNumber: "",
  email: "",
  projectAddress: "",
  city: "",
  source: "",
  salesExpert: "",
  status: "new",
  priority: "medium",
  lastContact: "",
  nextStep: "",
  estimatedValue: "",
  numberOfUnits: "",
  numberOfStops: "",
  elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
  usageTypes: [],
  environmentType: "",
  elevatorSpeed: "",
  capacity: "",
  doorType: "تمام اتوماتیک",
  doorOpeningType: "سانترال",
  floorDoorArrangement: "تک درب",
  doorWidth: "",
  doorHeight: "",
  doorStainlessSteelType: "",
  shaftIronwork: "ندارد",
  foundationIntrusionIntoShaft: "خیر",
  isShaftSuspended: "خیر",
  canPitBeDemolished: "خیر",
  isShaftSurroundingOpen: "خیر",
  shaftSurroundingCoveringTypes: [],
  shaftWidth: "",
  shaftDepth: "",
  shaftHeight: "",
  pitHeightWithoutFlooring: "",
  overheadWithoutFlooring: "",
  travelLength: "",
  requestedPackageType: "",
  description: "",
};

export const defaultCustomers: CustomerRecord[] = [
  {
    ...emptyCustomerFormValues,
    id: 1001,
    visitCoordinationPhone: "۰۲۱-۲۲۴۴۰۰۱۱",
    referenceNumber: "RN-1403-001",
    projectName: "برج سپهر",
    projectExpertise: "واحد فروش و فنی",
    reference: "معرفی مشتری قبلی",
    employerName: "شرکت عمران سپهر",
    requesterName: "مهندس رضایی",
    contactNumber: "۰۲۱-۲۲۴۴۰۰۱۱",
    email: "info@sepehr.example",
    projectAddress: "تهران، خیابان ولیعصر، برج سپهر",
    city: "تهران",
    source: "معرفی مشتری قبلی",
    salesExpert: "کارشناس فروش آتیس",
    status: "negotiating",
    priority: "high",
    lastContact: "۱۴۰۳/۰۷/۱۲",
    nextStep: "ارسال پیش‌فاکتور",
    estimatedValue: "۴.۸ میلیارد تومان",
    numberOfUnits: "۲",
    numberOfStops: "۱۲",
    elevatorType: "گیرلس بدون موتورخانه ام‌آر‌ال",
    usageTypes: ["مسافربر"],
    environmentType: "مسکونی",
    elevatorSpeed: "۱.۶",
    capacity: "۱۰ نفره",
    doorWidth: "۹۰",
    doorHeight: "۲۱۰",
    shaftWidth: "۲۲۰",
    shaftDepth: "۲۱۰",
    shaftHeight: "۳۸",
    requestedPackageType: "پکیج کامل آسانسور",
  },
  {
    ...emptyCustomerFormValues,
    id: 1002,
    visitDate: "۱۴۰۳/۰۷/۱۰",
    visitCoordinationPhone: "۰۲۱-۸۸۷۷۲۲۰۰",
    referenceNumber: "RN-1403-002",
    projectName: "مجتمع نگین",
    projectExpertise: "واحد فروش",
    reference: "وب‌سایت",
    employerName: "مجتمع تجاری نگین",
    requesterName: "خانم احمدی",
    contactNumber: "۰۲۱-۸۸۷۷۲۲۰۰",
    email: "purchase@negin.example",
    projectAddress: "کرج، بلوار اصلی، مجتمع نگین",
    city: "کرج",
    source: "وب‌سایت",
    salesExpert: "مدیر فروش",
    status: "visited",
    priority: "medium",
    lastContact: "۱۴۰۳/۰۷/۱۰",
    nextStep: "ثبت گزارش بازدید",
    estimatedValue: "۳.۲ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۸",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["مسافربر"],
    environmentType: "تجاری",
    elevatorSpeed: "۱",
    capacity: "۸ نفره",
    doorOpeningType: "چپ/راست",
    shaftIronwork: "دارد",
    shaftSurroundingCoveringTypes: ["بلوک سیمانی"],
  },
  {
    ...emptyCustomerFormValues,
    id: 1003,
    visitDate: "۱۴۰۳/۰۷/۰۸",
    visitCoordinationPhone: "۰۲۱-۹۹۰۰۱۱۲۲",
    referenceNumber: "RN-1403-003",
    projectName: "بخش توسعه بیمارستان",
    projectExpertise: "واحد مناقصات",
    reference: "مناقصه",
    employerName: "بیمارستان آتیه",
    requesterName: "واحد تدارکات",
    contactNumber: "۰۲۱-۹۹۰۰۱۱۲۲",
    email: "tender@atieh.example",
    projectAddress: "تهران، شهرک غرب، بیمارستان آتیه",
    city: "تهران",
    source: "مناقصه",
    salesExpert: "کارشناس فروش آتیس",
    status: "needsFollowUp",
    priority: "urgent",
    lastContact: "۱۴۰۳/۰۷/۰۸",
    nextStep: "هماهنگی بازدید فنی",
    estimatedValue: "۶.۱ میلیارد تومان",
    numberOfUnits: "۱",
    numberOfStops: "۸",
    elevatorType: "گیرلس با موتورخانه ام‌آر",
    usageTypes: ["بیمارستانی تخت‌بر", "برانکاردبر"],
    environmentType: "درمانی",
    elevatorSpeed: "۱",
    capacity: "۱۶۰۰ کیلوگرم",
    floorDoorArrangement: "تونلی",
    shaftSurroundingCoveringTypes: ["دیوار برشی"],
    requestedPackageType: "پکیج بیمارستانی",
  },
];
