export type CustomerPriority = "low" | "medium" | "high" | "urgent";
export type CustomerStatus = "new" | "negotiating" | "visited" | "needsFollowUp" | "proposalSent";

export type CustomerRecord = {
  id: number;
  visitDate: string;
  visitCoordinationPhone: string;
  referenceNumber: string;
  projectName: string;
  projectExpertise: string;
  reference: string;
  employerName: string;
  requesterName: string;
  contactNumber: string;
  email: string;
  projectAddress: string;
  provinceId: string;
  countyId: string;
  source: string;
  salesExpert: string;
  status: CustomerStatus;
  priority: CustomerPriority;
  lastContact: string;
  nextStep: string;
  estimatedValue: string;
  numberOfUnits: string;
  numberOfStops: string;
  elevatorType: string;
  usageTypes: string[];
  environmentType: string;
  elevatorSpeed: string;
  capacity: string;
  doorType: string;
  doorOpeningType: string;
  floorDoorArrangement: string;
  doorWidth: string;
  doorHeight: string;
  doorStainlessSteelType: string;
  shaftIronwork: string;
  foundationIntrusionIntoShaft: string;
  isShaftSuspended: string;
  canPitBeDemolished: string;
  isShaftSurroundingOpen: string;
  shaftSurroundingCoveringTypes: string[];
  shaftWidth: string;
  shaftDepth: string;
  shaftHeight: string;
  pitHeightWithoutFlooring: string;
  overheadWithoutFlooring: string;
  travelLength: string;
  requestedPackageType: string;
  description: string;
};
