/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as CrmCustomersRouteImport } from "./routes/crm/customers";
import { Route as CrmCustomersCustomerIdEditRouteImport } from "./routes/crm/customers.$customerId.edit";
import { Route as CrmCustomersNewRouteImport } from "./routes/crm/customers.new";
import { Route as CrmProjectsRouteImport } from "./routes/crm/projects";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as ReportsRouteImport } from "./routes/reports";
import { Route as SettingsRolesRouteImport } from "./routes/settings/roles";
import { Route as SettingsUsersRouteImport } from "./routes/settings/users";

const ReportsRoute = ReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: "/settings/users",
  path: "/settings/users",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: "/settings/roles",
  path: "/settings/roles",
  getParentRoute: () => rootRouteImport,
} as any);
const CrmProjectsRoute = CrmProjectsRouteImport.update({
  id: "/crm/projects",
  path: "/crm/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: "/crm/customers",
  path: "/crm/customers",
  getParentRoute: () => rootRouteImport,
} as any);
const CrmCustomersNewRoute = CrmCustomersNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => CrmCustomersRoute,
} as any);
const CrmCustomersCustomerIdEditRoute = CrmCustomersCustomerIdEditRouteImport.update({
  id: "/$customerId/edit",
  path: "/$customerId/edit",
  getParentRoute: () => CrmCustomersRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/reports": typeof ReportsRoute;
  "/crm/customers": typeof CrmCustomersRouteWithChildren;
  "/crm/projects": typeof CrmProjectsRoute;
  "/settings/roles": typeof SettingsRolesRoute;
  "/settings/users": typeof SettingsUsersRoute;
  "/crm/customers/new": typeof CrmCustomersNewRoute;
  "/crm/customers/$customerId/edit": typeof CrmCustomersCustomerIdEditRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/reports": typeof ReportsRoute;
  "/crm/customers": typeof CrmCustomersRouteWithChildren;
  "/crm/projects": typeof CrmProjectsRoute;
  "/settings/roles": typeof SettingsRolesRoute;
  "/settings/users": typeof SettingsUsersRoute;
  "/crm/customers/new": typeof CrmCustomersNewRoute;
  "/crm/customers/$customerId/edit": typeof CrmCustomersCustomerIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/reports": typeof ReportsRoute;
  "/crm/customers": typeof CrmCustomersRouteWithChildren;
  "/crm/projects": typeof CrmProjectsRoute;
  "/settings/roles": typeof SettingsRolesRoute;
  "/settings/users": typeof SettingsUsersRoute;
  "/crm/customers/new": typeof CrmCustomersNewRoute;
  "/crm/customers/$customerId/edit": typeof CrmCustomersCustomerIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/reports"
    | "/crm/customers"
    | "/crm/projects"
    | "/settings/roles"
    | "/settings/users"
    | "/crm/customers/new"
    | "/crm/customers/$customerId/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/reports"
    | "/crm/customers"
    | "/crm/projects"
    | "/settings/roles"
    | "/settings/users"
    | "/crm/customers/new"
    | "/crm/customers/$customerId/edit";
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/reports"
    | "/crm/customers"
    | "/crm/projects"
    | "/settings/roles"
    | "/settings/users"
    | "/crm/customers/new"
    | "/crm/customers/$customerId/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  ProfileRoute: typeof ProfileRoute;
  ReportsRoute: typeof ReportsRoute;
  CrmCustomersRoute: typeof CrmCustomersRouteWithChildren;
  CrmProjectsRoute: typeof CrmProjectsRoute;
  SettingsRolesRoute: typeof SettingsRolesRoute;
  SettingsUsersRoute: typeof SettingsUsersRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/reports": {
      id: "/reports";
      path: "/reports";
      fullPath: "/reports";
      preLoaderRoute: typeof ReportsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/users": {
      id: "/settings/users";
      path: "/settings/users";
      fullPath: "/settings/users";
      preLoaderRoute: typeof SettingsUsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/roles": {
      id: "/settings/roles";
      path: "/settings/roles";
      fullPath: "/settings/roles";
      preLoaderRoute: typeof SettingsRolesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/crm/projects": {
      id: "/crm/projects";
      path: "/crm/projects";
      fullPath: "/crm/projects";
      preLoaderRoute: typeof CrmProjectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/crm/customers": {
      id: "/crm/customers";
      path: "/crm/customers";
      fullPath: "/crm/customers";
      preLoaderRoute: typeof CrmCustomersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/crm/customers/new": {
      id: "/crm/customers/new";
      path: "/new";
      fullPath: "/crm/customers/new";
      preLoaderRoute: typeof CrmCustomersNewRouteImport;
      parentRoute: typeof CrmCustomersRoute;
    };
    "/crm/customers/$customerId/edit": {
      id: "/crm/customers/$customerId/edit";
      path: "/$customerId/edit";
      fullPath: "/crm/customers/$customerId/edit";
      preLoaderRoute: typeof CrmCustomersCustomerIdEditRouteImport;
      parentRoute: typeof CrmCustomersRoute;
    };
  }
}

interface CrmCustomersRouteChildren {
  CrmCustomersNewRoute: typeof CrmCustomersNewRoute;
  CrmCustomersCustomerIdEditRoute: typeof CrmCustomersCustomerIdEditRoute;
}

const CrmCustomersRouteChildren: CrmCustomersRouteChildren = {
  CrmCustomersNewRoute: CrmCustomersNewRoute,
  CrmCustomersCustomerIdEditRoute: CrmCustomersCustomerIdEditRoute,
};

const CrmCustomersRouteWithChildren = CrmCustomersRoute._addFileChildren(CrmCustomersRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  CrmCustomersRoute: CrmCustomersRouteWithChildren,
  CrmProjectsRoute: CrmProjectsRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsUsersRoute: SettingsUsersRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
